import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

export type BlogPillar = "Business Economics" | "Operations" | "Technology";

const VALID_PILLARS: BlogPillar[] = ["Business Economics", "Operations", "Technology"];

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  author: string;
  publishedAt: string;
  category: string;
  /** RidgeHQ Academy topic pillar (Phase 6 of the AI-discoverability initiative). */
  pillar: BlogPillar;
  readingTime: string;
  /**
   * When true, the post is hidden from the blog index, its route, and the
   * sitemap in production builds. It stays visible in local dev so it can be
   * previewed before the claims are verified and the flag is removed.
   */
  draft?: boolean;
}

const BLOG_DIR = path.join(process.cwd(), "content/blog");

const WORDS_PER_MINUTE = 225;

function computeReadingTime(content: string): string {
  const words = content.trim().split(/\s+/).filter(Boolean).length;
  return `${Math.max(1, Math.round(words / WORDS_PER_MINUTE))} min read`;
}

/**
 * Reads every `.md` file in `content/blog/` at build time. The filename (minus
 * `.md`) is the slug; YAML frontmatter supplies the metadata; the body is the
 * Markdown content. Drop a file in the folder and it appears — no index to keep
 * in sync.
 *
 * Frontmatter field names accept two spellings so posts authored directly and
 * posts generated by the Brain vault content pipeline both load unchanged:
 *   excerpt  | description
 *   publishedAt | date
 * `category` defaults to "Product" and `author` to "RidgeHQ Team" when absent.
 * `pillar` is required ("Business Economics" | "Operations" | "Technology") —
 * it groups the /blog index into the RidgeHQ Academy's three topic pillars.
 */
function loadBlogPosts(): BlogPost[] {
  const files = fs.readdirSync(BLOG_DIR).filter((file) => file.endsWith(".md"));

  const posts = files.map((file): BlogPost => {
    const raw = fs.readFileSync(path.join(BLOG_DIR, file), "utf8");
    const { data, content } = matter(raw);

    const excerpt = data.excerpt ?? data.description;
    // js-yaml parses an unquoted `2026-09-08` as a Date; normalise to YYYY-MM-DD.
    const rawDate = data.publishedAt ?? data.date;
    const publishedAt =
      rawDate instanceof Date ? rawDate.toISOString().slice(0, 10) : rawDate;

    const missing: string[] = [];
    if (!data.title) missing.push("title");
    if (!excerpt) missing.push("excerpt (or description)");
    if (!publishedAt) missing.push("publishedAt (or date)");
    if (!data.pillar) missing.push("pillar");
    if (missing.length > 0) {
      throw new Error(
        `Blog post content/blog/${file} is missing required frontmatter: ${missing.join(", ")}`,
      );
    }
    if (!VALID_PILLARS.includes(data.pillar)) {
      throw new Error(
        `Blog post content/blog/${file} has an invalid pillar "${data.pillar}" — must be one of: ${VALID_PILLARS.join(", ")}`,
      );
    }

    return {
      slug: file.replace(/\.md$/, ""),
      title: data.title,
      excerpt,
      content: content.trim(),
      author: data.author ?? "RidgeHQ Team",
      publishedAt: String(publishedAt).slice(0, 10),
      category: data.category ?? "Product",
      pillar: data.pillar as BlogPillar,
      readingTime: computeReadingTime(content),
      draft: data.draft ?? false,
    };
  });

  return posts.sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
}

export const blogPosts: BlogPost[] = loadBlogPosts();

/** Drafts render in local dev for preview but are excluded from production. */
export const visibleBlogPosts: BlogPost[] = blogPosts.filter(
  (post) => process.env.NODE_ENV === "development" || !post.draft,
);
