export interface VerticalFeatureSection {
  heading: string;
  body: string;
  points: string[];
}

export interface VerticalWorkflowStep {
  title: string;
  detail: string;
}

export interface VerticalOutcome {
  label: string;
  detail: string;
}

export interface Vertical {
  id: string;
  name: string;
  slug: string;
  heroHeadline: string;
  heroDescription: string;
  painPoint: string;
  keyCapability: string;
  representativeFlow: string[];
  constraints: string[];
  faqs: { question: string; answer: string }[];
  /**
   * Extended marketing content. Added progressively per vertical — the
   * template renders these sections only when the data is present, so a
   * vertical without them still renders the core layout.
   */
  heroProofPoints?: string[];
  featureSections?: VerticalFeatureSection[];
  workflow?: VerticalWorkflowStep[];
  outcomes?: VerticalOutcome[];
}

export const verticals: Vertical[] = [
  {
    id: 'dive-centers',
    name: 'Dive Centers',
    slug: 'dive-centers',
    heroHeadline: 'From first click to final dive, on one system.',
    heroDescription: 'Generic booking tools do not understand boats, two-tank days, kit prep, or per-diver medicals. RidgeHQ puts dive-specific rosters, waivers, payments, and multi-channel sales in one place.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Boat manifests from the same schedule',
      'Per-participant digital waivers, built in',
    ],
    painPoint: 'A typical dive center sells on a booking widget, plans the boat on a whiteboard, keeps kit sizing in a folder, and logs course progress in a spreadsheet. Every course that fills online is re-typed onto the manifest by hand, every gear swap is checked from memory, and no screen shows the whole day at once.',
    keyCapability: 'Every booking arrives on the day plan with the diver, their certification level, and their stored kit sizing attached — so the manifest, the ratio check, and the gear draw-down build themselves instead of being copied across three tools.',
    representativeFlow: [
      'A diver books an Open Water course online and answers the medical questions.',
      'RidgeHQ reserves cylinders and rental kit in the diver\'s sizes.',
      'An instructor is matched by language and certification level.',
      'The boat manifest updates with the correct headcount, weights, and crew.',
      'Dive logs and course progress are saved to the diver\'s profile.',
    ],
    featureSections: [
      {
        heading: 'One checkout for the website, the desk, and your agents',
        body: 'Your booking widget, the front-desk register, phone reservations, and agent referrals all write to the same availability and the same order. A course that sells online shows full at the desk a moment later — no re-keying, no double-booked tanks.',
        points: [
          'Booking widget for courses, fun dives, and packages, taking a deposit or the full amount through your own gateway',
          'Front-desk POS for walk-in dives, gear hire, and retail on a single ticket, with register open / close and cash reconciliation',
          'Agent and partner reservations recorded with their commission, ready to settle',
          'Medical, experience, and equipment questions collected at the point of booking',
          '0% platform commission on direct bookings — your marketing revenue stays yours',
        ],
      },
      {
        heading: 'Boat days that are ready before the lines are off',
        body: 'Each confirmed booking lands on the schedule carrying the diver\'s level and sizing. Build the manifest from that plan in a couple of taps, and RidgeHQ holds you to seat count, weight, and instructor-to-diver ratios.',
        points: [
          'Manifests generated from the day plan and checked against passenger capacity and assigned crew',
          'Instructor-to-diver ratios enforced per course type before a session can confirm',
          'Wetsuit, BCD, fin, and weight sizing pulled from each profile onto the check-in list',
          'Tide, visibility, and water-temperature context on the session, with per-activity suitability thresholds',
          'Cylinder and specialty-gear stock drawn down as sessions and rentals are booked',
        ],
      },
      {
        heading: 'The admin that used to eat your evenings',
        body: 'Waivers, confirmations, reminders, and certification records are part of the booking rather than a stack of separate jobs. When a booking changes, the money trail stays correct on its own.',
        points: [
          'Per-participant digital waivers with typed e-signature and conditional medical questions — included, not a metered add-on',
          'Automated confirmations and pre-arrival reminders with joining instructions',
          'Course completion recorded per diver, producing the record your agency paperwork needs',
          'Order immutability: an edit to a paid order creates a credit note instead of silently rewriting it',
          'An AI copilot that reads the day and can reschedule a session or move a diver between boats, each behind a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Book 24/7', detail: 'A diver books an Open Water course or a two-tank trip on your site, pays a deposit, and answers the medical and experience questions.' },
      { title: 'Take payment', detail: 'The deposit or full amount is captured through your own gateway; any balance is scheduled and tracked against the order.' },
      { title: 'Collect the waiver', detail: 'The participant signs the liability waiver and any conditional medical questions before arrival, linked to their profile.' },
      { title: 'Plan the dive', detail: 'The session picks up an instructor by language and level, and reserves cylinders and rental kit in the diver\'s sizes.' },
      { title: 'Run the manifest', detail: 'The boat list builds from the day plan with headcount, weights, and crew, flagging any ratio or capacity breach.' },
      { title: 'Close the day', detail: 'Dive logs and course progress are recorded, balances settle at the desk, and the day\'s totals land in reporting.' },
    ],
    outcomes: [
      { label: 'Sales while the shop is shut', detail: 'The widget takes courses and trips overnight, straight into the calendar your team works from.' },
      { label: 'One picture of the day', detail: 'Bookings, boats, staff, gear, and payments move together — you stop being the link between five tools.' },
      { label: 'Enter a booking once', detail: 'Manifests, waivers, ratios, and reporting read from it instead of asking you to copy it.' },
      { label: 'Works at the dock', detail: 'Instructors see their sessions, diver lists, and kit sizing on a phone, not a printout left in the office.' },
    ],
    constraints: [
      'Boat passenger capacity, weight distribution, and crew assignment',
      'Instructor-to-diver ratios that vary by course and agency standard',
      'Cylinder, weight, and specialty-gear stock (nitrox, drysuit, camera)',
      'Certification prerequisites and medical clearance per course',
      'Tide windows, visibility, and water temperature for each site',
    ],
    faqs: [
      { question: 'Does it replace my PADI or SSI portal?', answer: 'No. RidgeHQ is your operational system of record — it tracks certification level and course completion for your manifests and hands you the record you need, while the certification itself is still issued through your agency.' },
      { question: 'Can it run more than one boat?', answer: 'Yes. Each vessel has its own manifest, capacity, crew roster, and departure time, and the day plan shows them side by side.' },
      { question: 'How do the digital waivers work?', answer: 'A waiver goes out with every booking and is signed per participant with a typed e-signature. You can add conditional medical questions that only expand when a diver answers yes. It is part of the platform, not a paid extra.' },
      { question: 'What happens when a diver reschedules or a trip is cancelled?', answer: 'A change to a paid order produces a credit note rather than overwriting it, so your accounts stay reconcilable. Moving a diver to another session is a one-step, reversible action.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission. You pay your normal payment-gateway fee and a flat monthly subscription.' },
      { question: 'Can the AI copilot change live bookings?', answer: 'It reads your schedule and bookings and can carry out reversible scheduling actions — rescheduling a session, reassigning a diver — each with a confirm step. Money-moving actions are logged and left for you to complete.' },
      { question: 'Can staff see the day from a phone?', answer: 'Yes. Instructors and crew get their sessions, diver lists, and kit sizing on mobile, so the boat is not waiting on a printout left in the office.' },
      { question: 'Does it close the day and export for accounting?', answer: 'Yes. The daily close reconciles deposits, balances, and credit notes, with revenue-by-origin reporting and exports for your bookkeeper.' },
    ],
  },
  {
    id: 'surf-schools',
    name: 'Surf Schools',
    slug: 'surf-schools',
    heroHeadline: 'Fill more classes and keep the whole day in sync.',
    heroDescription: 'Stop juggling spreadsheets, group chats, and last-minute changes. RidgeHQ brings bookings, tide-aware scheduling, instructor planning, payments, and partner sales into one live system.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Tide and swell context on every session',
      'Move a whole group in one action',
    ],
    painPoint: 'Surf timetables move with the tide and the forecast, and most schools re-plan by hand — messaging instructors, chasing wetsuit sizes, rebooking groups one reply at a time. The booking site, the board rack, and the progression sheet never quite agree.',
    keyCapability: 'The day plan carries the tide window and swell forecast for your break alongside wetsuit and board sizing and instructor level — so when conditions turn you reschedule a whole group and the resources and messages follow.',
    representativeFlow: [
      'A group books a three-day beginner camp online.',
      'RidgeHQ checks instructor availability against the incoming swell.',
      'Foamies and wetsuits are reserved from the rental fleet.',
      'If conditions change, the group is bulk-rescheduled and everyone is messaged.',
      'Each student\'s progress is tracked across the three days.',
    ],
    featureSections: [
      {
        heading: 'Sell everywhere, one live availability',
        body: 'Website bookings, front-desk sales, and multi-day camp packages all write to the same session capacity. A camp that sells out online is full at the desk the moment it happens.',
        points: [
          'Booking widget for lessons, courses, and camp packages with a deposit or full payment',
          'Front-desk POS for walk-in lessons, board and wetsuit hire, and retail on one ticket',
          'Multi-day camps that block the instructor and the equipment for the whole run',
          'Custom questions at checkout — ability level, height and weight, board preference',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'Schedule around the tide, re-plan in one move',
        body: 'Every session shows the tide window and swell forecast for your spot next to the roster and the board list. When the forecast turns, reschedule the group in a single action and everyone is notified.',
        points: [
          'Tide, swell height, and swell period context on each session from your spot\'s forecast',
          'Per-activity suitability thresholds, so a beginner group is flagged when the surf is too big',
          'Bulk reschedule a group or a whole day, with automated messages to every participant',
          'Wetsuit and board sizing reserved from the rental fleet against each booking',
          'Instructor assignment by certification level and language',
        ],
      },
      {
        heading: 'Admin on autopilot',
        body: 'Waivers, confirmations, reminders, and progress records live on the booking. A change to a paid order stays reconcilable instead of quietly rewriting the numbers.',
        points: [
          'Per-participant digital waivers with typed e-signature and conditional health questions — built in',
          'Automated confirmations and pre-session reminders with meeting point and kit list',
          'Progression logged per student so the next instructor knows where to start',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the day and can reschedule a session or move students between groups, with a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Book 24/7', detail: 'A group books a three-day beginner camp online, pays a deposit, and answers the experience and health questions.' },
      { title: 'Secure payment', detail: 'The deposit is captured through your own gateway; the balance is scheduled and tracked against the order.' },
      { title: 'Capture the waiver', detail: 'Each participant signs the waiver and any conditional health questions before the first session.' },
      { title: 'Assign fast', detail: 'Sessions are placed against the tide window, an instructor is matched by level, and foamies and wetsuits are reserved in the right sizes.' },
      { title: 'Re-plan on the forecast', detail: 'If the swell turns, the whole group is rescheduled in one move and every participant is messaged automatically.' },
      { title: 'Close clean', detail: 'Progress is logged per student, balances settle at the desk, and the day\'s totals land in reporting.' },
    ],
    outcomes: [
      { label: 'Bookings after hours', detail: 'The widget sells lessons and camps overnight into the same calendar your instructors work from.' },
      { label: 'Weather moves, you do not scramble', detail: 'One reschedule action moves the group, the instructor, and the boards, and notifies everyone.' },
      { label: 'Enter a booking once', detail: 'Rosters, waivers, kit, and progress read from it instead of a separate sheet.' },
      { label: 'Works on the beach', detail: 'Instructors see their sessions, participant lists, and sizing from a phone.' },
    ],
    constraints: [
      'Tide windows and safe swell height for each ability level',
      'Wetsuit and board sizing matched to student size and skill',
      'Instructor availability by certification level (for example ISA L1 vs L2) and language',
      'Rental fleet shared between lessons and walk-in hire',
      'Multi-day camp blocks that span several sessions',
    ],
    faqs: [
      { question: 'How does it handle a bad forecast?', answer: 'Each session carries the tide and swell context for your spot. When conditions turn, you bulk-reschedule the affected sessions or a whole day and every participant is notified in one step.' },
      { question: 'Can it manage private and group lessons together?', answer: 'Yes. The calendar handles private sessions, open group classes, and multi-day camps at once, each with its own capacity and instructor ratio.' },
      { question: 'Does it track student progression?', answer: 'Yes. Progress is logged per student against your progression steps, so the next instructor picks up exactly where the last one left off.' },
      { question: 'Can we rent boards and wetsuits through the same system?', answer: 'Yes. The rental fleet is shared between lessons and walk-in hire, so kit committed to a class is not offered to a walk-in, and both go on one ticket.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'What happens to the money when a camp booking changes?', answer: 'A change to a paid order produces a credit note rather than overwriting it, so your accounts stay reconcilable.' },
      { question: 'Can we reuse a weekly plan instead of rebuilding every day?', answer: 'Yes. Duplicate a set of sessions forward and adjust individual days, rather than rebuilding the timetable from scratch each week.' },
      { question: 'Can instructors work from their phones on the beach?', answer: 'Yes. Each instructor sees their sessions, group lists, and student notes on mobile, kept current as the day changes.' },
    ],
  },
  {
    id: 'kitesurf-schools',
    name: 'Kitesurf Schools',
    slug: 'kitesurf-schools',
    heroHeadline: 'Sell more sessions, reschedule fast when the wind shifts.',
    heroDescription: 'Generic tools do not get wind windows, last-minute reshuffles, or multi-session courses. RidgeHQ gives you multichannel sales, bulk messaging, quick scheduling, and forms that adapt.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Wind speed and direction on every session',
      'Kite and harness sizing tied to student weight',
    ],
    painPoint: 'Kite lessons only run inside a wind window, so schools lose the morning to "wind is on" messages and then a hunt for a kite in the right size. The booking tool, the gear board, and the progression cards sit in three places, and none of them read the forecast.',
    keyCapability: 'Sessions hold the wind forecast for your spot, and confirming one reserves the right kite size and harness for each student\'s weight — so a wind window becomes a full, kitted, briefed lesson in minutes.',
    representativeFlow: [
      'A student books a block of six instruction hours.',
      'Lessons are scheduled but flagged wind-dependent.',
      'When the forecast lands in your window, the instructor is confirmed.',
      'Kite sizes and harnesses are reserved against the student\'s weight.',
      'Progress is logged step by step for IKO or VDWS sign-off.',
    ],
    featureSections: [
      {
        heading: 'Sell instruction blocks across every channel',
        body: 'Website bookings, front-desk sales, and pre-paid hour blocks all draw from the same instructor capacity. An hours package bought online is visible to the team immediately, and hours are drawn down as they are used.',
        points: [
          'Booking widget for lesson blocks, courses, and taster sessions with a deposit or full payment',
          'Pre-paid hour packages tracked per student and drawn down session by session',
          'Front-desk POS for walk-in lessons, gear hire, and retail on one ticket',
          'Agent and hotel referrals recorded with their commission, ready to settle',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'Wind-dependent scheduling that actually holds the wind',
        body: 'Each session shows the forecast wind speed and direction for your spot next to the roster and the kite board. Provisional lessons stay flagged as wind-dependent until you confirm, and confirming reserves matched gear.',
        points: [
          'Wind speed, direction, and gust context on the session from your spot\'s forecast',
          'Per-activity thresholds with a minimum and a maximum wind limit, so a session is flagged when it is too light or too strong',
          'Kite size and harness reserved against student weight when a session confirms',
          'Radio helmet and safety-boat availability scheduled alongside the instructor',
          'Confirm or postpone a whole session in one move, with automated messages to every student',
        ],
      },
      {
        heading: 'Progression and comms on autopilot',
        body: 'IKO or VDWS progression, waivers, and confirmations travel with the booking. Money-affecting changes leave a clean trail instead of overwriting a paid order.',
        points: [
          'Progression logged step by step per student for IKO / VDWS sign-off',
          'Per-participant digital waivers with typed e-signature and conditional health questions — built in',
          'Batch confirmations and "wind is on" messages with meeting point and kit',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the day and can reschedule or reassign students, with a confirm step on riskier actions',
        ],
      },
    ],
    workflow: [
      { title: 'Book the block', detail: 'A student books a six-hour instruction block online, pays up front, and gives their weight and experience.' },
      { title: 'Credit the hours', detail: 'Payment is captured through your own gateway and the hours are credited to the student\'s profile.' },
      { title: 'Collect the waiver', detail: 'The student signs the waiver and conditional health questions before the first session.' },
      { title: 'Make the wind call', detail: 'Provisional sessions stay flagged wind-dependent; when the forecast lands in your window you confirm and everyone is messaged.' },
      { title: 'Kit and brief', detail: 'Confirming reserves the right kite size and harness for the student\'s weight, plus radio helmet and safety boat.' },
      { title: 'Sign off', detail: 'Progression is logged per student, hours are drawn down, and the day\'s totals land in reporting.' },
    ],
    outcomes: [
      { label: 'Wind windows become lessons', detail: 'One confirm action turns a forecast into a kitted, briefed session with the whole group notified.' },
      { label: 'Expensive gear stays tracked', detail: 'Kites and harnesses committed to a session are never double-booked to a walk-in.' },
      { label: 'Hours never go missing', detail: 'Pre-paid blocks are drawn down automatically, so nobody argues about how many are left.' },
      { label: 'One picture of the day', detail: 'Forecast, roster, gear, and progression sit in one view instead of three.' },
    ],
    constraints: [
      'Wind window with both a minimum and a maximum safe speed',
      'Wind direction suitable for the teaching zone',
      'Kite size and harness matched to student weight and live wind',
      'Radio helmet and safety-boat availability per lesson',
      'Pre-paid instruction hours tracked per student',
    ],
    faqs: [
      { question: 'Can we manage boat-assisted lessons?', answer: 'Yes. Safety-boat availability is scheduled alongside your instructors, so a lesson that needs the boat cannot confirm when the boat is already out.' },
      { question: 'Does it track student levels?', answer: 'Yes. Progress is logged against IKO or VDWS progression steps, so the next instructor knows exactly where to pick up.' },
      { question: 'How does it handle the wind call?', answer: 'Sessions carry the forecast wind speed and direction for your spot and stay flagged wind-dependent until you confirm. Confirming or postponing a session messages every student in one step.' },
      { question: 'Can it stop us double-booking kites?', answer: 'Yes. A kite size and harness reserved for a confirmed session is removed from the pool, so it is not offered to another lesson or a walk-in.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'What happens to pre-paid hours if a student cancels a session?', answer: 'Unused hours stay on the student\'s profile. A change to a paid order creates a credit note rather than overwriting it.' },
      { question: 'Can we sell rentals as well as lessons?', answer: 'Yes. Rentals are bookable items in the same catalogue and draw from the same gear availability as your lessons.' },
      { question: 'Does it handle the end-of-day POS close and reporting?', answer: 'Yes. Close the register with reconciled totals, and pull sales, cancellation, and occupancy reports with exports for accounting.' },
    ],
  },
  {
    id: 'sailing-schools',
    name: 'Sailing Schools',
    slug: 'sailing-schools',
    heroHeadline: 'From enrolment to the last tack, one system.',
    heroDescription: 'Generic booking tools struggle with summer courses, private coaching, and fleet charter at once. RidgeHQ keeps every service in one place so you sell across channels and keep sessions on time.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Vessels, inspection dates, and crew in one place',
      'Multi-day courses block boat and instructor',
    ],
    painPoint: 'A sailing school is a scheduling puzzle: a five-day course needs the right boat for five days, a qualified skipper for the same five days, and no clash with a maintenance haul-out or a weekend charter. Run that across a fleet on a spreadsheet and something gets double-booked.',
    keyCapability: 'The fleet — each vessel\'s capacity, inspection and licence dates, and assigned crew — sits inside the same calendar as your courses, so a multi-day course reserves the boat and the skipper together and refuses to clash.',
    representativeFlow: [
      'A client books a five-day Competent Crew course.',
      'RidgeHQ reserves a specific keelboat for the duration.',
      'A qualified skipper is assigned for the five-day block.',
      'Joining instructions and a packing list go out automatically.',
      'After the course, the boat drops into a turnaround block.',
    ],
    featureSections: [
      {
        heading: 'Courses and charters from one calendar',
        body: 'Instruction courses and bareboat or skippered charters draw from the same fleet availability, so a boat booked for a weekend charter is not offered to a course starting Monday.',
        points: [
          'Booking widget for courses, progression pathways, and charters with a deposit or full payment',
          'Skippered and bareboat charters managed alongside taught courses',
          'Front-desk POS for day sails, membership, and retail on one ticket',
          'Referrals and agents recorded with agreed rates and commission tracking',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'Fleet management inside the schedule',
        body: 'Every vessel carries its passenger capacity, registration, and inspection, licence, and insurance expiry dates, plus its assigned crew. Maintenance and turnaround blocks sit on the same calendar as the courses.',
        points: [
          'Vessel records with capacity, registration, and inspection / licence / insurance expiry tracking',
          'Crew assignment per vessel, so only qualified skippers can be scheduled to it',
          'Maintenance, haul-out, and turnaround blocks that take a boat out of availability',
          'Multi-day courses that block both the vessel and the instructor for the full run',
          'Minimum-crew limits enforced per vessel before a session can confirm',
        ],
      },
      {
        heading: 'Admin on autopilot',
        body: 'Joining instructions, waivers, and progression records travel with the booking, and money-affecting changes leave a clean trail.',
        points: [
          'Automated joining instructions, packing lists, and pre-course reminders',
          'Per-participant digital waivers with typed e-signature, conditional health questions, and guardian consent for minors — built in',
          'Progression logged per student across a multi-day course for certificate sign-off',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the schedule and can reschedule a session or reassign crew, with a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Book the course', detail: 'A client books a five-day Competent Crew course online and pays a deposit.' },
      { title: 'Take payment', detail: 'The deposit is captured through your own gateway; the balance is scheduled against the order.' },
      { title: 'Hold boat and skipper', detail: 'A specific keelboat is reserved for the five days and a qualified skipper is assigned to the same block.' },
      { title: 'Brief the crew', detail: 'Each participant signs the waiver and health questions; joining instructions and a packing list go out automatically.' },
      { title: 'Run the course', detail: 'The multi-day block shows on the agenda holding boat and instructor; progression is logged each day.' },
      { title: 'Turn the boat around', detail: 'After the course the boat drops into a cleaning and turnaround block, and the day\'s totals land in reporting.' },
    ],
    outcomes: [
      { label: 'No more double-booked boats', detail: 'Courses, charters, and maintenance share one calendar, so a vessel can only be in one place.' },
      { label: 'Only qualified crew get scheduled', detail: 'Crew assignment per vessel means an unqualified skipper cannot be dropped onto the wrong boat.' },
      { label: 'Compliance dates in view', detail: 'Inspection, licence, and insurance expiry are tracked on the vessel, not remembered.' },
      { label: 'One picture of the operation', detail: 'Fleet, instructors, bookings, and payments move together instead of across separate tools.' },
    ],
    constraints: [
      'Vessel availability against courses, charters, and maintenance blocks',
      'Skipper and instructor qualification requirements per vessel',
      'Minimum and maximum crew limits for specific boats',
      'Inspection, licence, and insurance expiry dates per vessel',
      'Multi-day course blocks spanning consecutive days',
    ],
    faqs: [
      { question: 'Can we handle bareboat charters as well as courses?', answer: 'Yes. Taught courses and bareboat or skippered charters draw from the same fleet availability, so the two can never book the same boat for overlapping dates.' },
      { question: 'How are multi-day courses shown?', answer: 'A multi-day course appears as a single block on the agenda that holds both the vessel and the instructor for the whole run.' },
      { question: 'Does it track vessel compliance?', answer: 'Each vessel records its registration and its inspection, licence, and insurance expiry dates, and is flagged as those dates approach.' },
      { question: 'Can it stop an unqualified skipper being scheduled?', answer: 'Crew are assigned per vessel, so only the skippers cleared for a boat can be scheduled onto it.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'What happens if a course booking changes?', answer: 'A change to a paid order creates a credit note rather than overwriting it, so your accounts stay reconcilable.' },
      { question: 'Can we take deposits or partial payments to hold a place?', answer: 'Yes. Take a deposit or the full amount at booking; the balance is scheduled and tracked against the order until it is settled.' },
      { question: 'Can we give instructors limited access on mobile?', answer: 'Yes. Staff roles control what each person can see and change, and instructors get their schedule and crew lists on a phone.' },
    ],
  },
  {
    id: 'windsurf-schools',
    name: 'Windsurf Schools',
    slug: 'windsurf-schools',
    heroHeadline: 'Run a high-volume watersports centre at full speed.',
    heroDescription: 'Built for busy lesson and rental floors — windsurf, wingfoil, SUP. Sell through more channels, keep one live schedule for the whole team, and run clean check-ins without spreadsheet chaos.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Lessons and walk-in hire share one fleet',
      'Live status on every board and rig',
    ],
    painPoint: 'A busy windsurf centre turns over gear all day and rents storage racks all season, while also teaching wind-dependent lessons. On paper you never quite know what is on the water, what is due back, or whether the board a lesson needs is already out with a walk-in.',
    keyCapability: 'One shared fleet across lessons and walk-in hire, with each board and rig tracked out and back and every storage rack billed on schedule — so the desk always knows what is available right now.',
    representativeFlow: [
      'A client walks in for a two-hour equipment rental.',
      'Staff assign a specific board and rig on the POS.',
      'The return time is tracked, with an overdue flag at the desk.',
      'The client books a lesson for the next day onto the same profile.',
      'Both are settled on one invoice.',
    ],
    featureSections: [
      {
        heading: 'Fast walk-in hire, no second system',
        body: 'The front-desk POS moves a walk-in from counter to water in a few taps, assigning a specific board and rig and starting the return clock. Lessons booked online land in the same calendar.',
        points: [
          'Front-desk POS for rapid walk-in rental, retail, and add-ons on one ticket',
          'Booking widget for lessons, courses, and pre-booked hire with a deposit or full payment',
          'Return times tracked per item, with an overdue flag at the desk',
          'Card-on-file for repeat renters, with balances tracked against the order',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'One fleet, shared between lessons and hire',
        body: 'Boards and rigs committed to a lesson are not offered to a walk-in, and the reverse. Every unit shows its status — available, out, due back, in for repair.',
        points: [
          'Shared board and rig inventory across taught lessons and walk-in hire',
          'Volume and rig size matched to student weight and skill level',
          'Wind speed and direction context on lesson sessions from your spot\'s forecast',
          'Per-activity thresholds separating beginner-safe from advanced-only conditions',
          'Maintenance status that pulls a damaged board out of availability until it is fixed',
        ],
      },
      {
        heading: 'Season-long storage and clean books',
        body: 'Storage racks are managed and billed like any other resource, and money-affecting changes leave a clean trail.',
        points: [
          'Long-term storage racks tracked per client and billed on a recurring schedule',
          'Per-participant digital waivers with typed e-signature and conditional health questions — built in',
          'Automated confirmations and reminders for booked lessons and hire',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the day and can reschedule a lesson or reassign an instructor, with a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Take the walk-in', detail: 'A client asks for a two-hour rental; the desk assigns a specific board and rig on the POS.' },
      { title: 'Take payment', detail: 'The rental and any retail go on one ticket, paid through your own gateway.' },
      { title: 'Send it out', detail: 'The item is marked out with a return time; the desk sees an overdue flag if it runs late.' },
      { title: 'Add a lesson', detail: 'The client books a lesson for the next day; it is added to their profile and the same calendar.' },
      { title: 'Check it back in', detail: 'Gear is returned, any damage is logged, and the balance settles on the existing ticket.' },
      { title: 'Close the day', detail: 'Outstanding items, storage billing, and the day\'s takings land in reporting.' },
    ],
    outcomes: [
      { label: 'You know what is on the water', detail: 'Every board and rig shows available, out, due back, or in for repair — in real time.' },
      { label: 'Lessons and hire stop colliding', detail: 'Kit committed to a class is never handed to a walk-in, and the reverse.' },
      { label: 'Storage bills itself', detail: 'Season racks sit on a recurring charge instead of a note in a drawer.' },
      { label: 'One ticket per customer', detail: 'Rental, lessons, and retail settle together instead of across separate systems.' },
    ],
    constraints: [
      'Wind speed and direction thresholds for beginner vs advanced lessons',
      'Board volume and rig size matched to student weight and skill',
      'Shared fleet split between taught lessons and walk-in hire',
      'Return times and overdue tracking for items on the water',
      'Physical storage rack availability and recurring billing',
    ],
    faqs: [
      { question: 'Can we manage long-term gear storage for clients?', answer: 'Yes. Storage racks are tracked per client and billed on a recurring schedule, alongside the rest of the operation.' },
      { question: 'Does it work for fast walk-in rentals?', answer: 'Yes. The POS is built for rapid walk-in processing — assign a specific board and rig, start the return clock, and take payment in a few taps.' },
      { question: 'Can it stop a lesson and a walk-in taking the same board?', answer: 'Yes. The fleet is shared, so a unit committed to a lesson is removed from the walk-in pool and the reverse.' },
      { question: 'How does it handle wind-dependent lessons?', answer: 'Lesson sessions carry the forecast wind speed and direction for your spot, with per-activity limits so a beginner session is flagged when it is too strong.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'What happens when a booking changes?', answer: 'A change to a paid order creates a credit note rather than overwriting it, so your accounts stay reconcilable.' },
      { question: 'How does the register close at the end of the day?', answer: 'A register opens and closes with its own cash reconciliation, and the day\'s takings roll into your sales and occupancy reports.' },
      { question: 'Does it give us accounting-ready exports?', answer: 'Yes. Register closes, invoices, and credit notes export in a structured form for your bookkeeper.' },
    ],
  },
  {
    id: 'outdoor-whitewater',
    name: 'Outdoor & Whitewater',
    slug: 'outdoor-whitewater',
    heroHeadline: 'Run your outdoor centre in flow.',
    heroDescription: 'Rafting, canyoning, and guided kayak trips move fast, sell in groups, and depend on clean logistics. RidgeHQ keeps website sales, POS, agents, payments, and participant forms connected.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Headcount drives rafts, guides, and shuttle seats',
      'A signed waiver for every participant',
    ],
    painPoint: 'A single rafting or canyoning trip is a logistics chain: enough boats for the headcount, enough guides for the ratio, enough shuttle seats to reach the put-in, and a signed waiver for every person. Miss one link and the trip runs short-handed or leaves someone at the depot.',
    keyCapability: 'A booking\'s headcount drives the whole chain — rafts, guides at your ratio, and shuttle seats are reserved together, and nobody boards without a signed waiver on file.',
    representativeFlow: [
      'A corporate group of 30 books a half-day rafting trip.',
      'RidgeHQ sizes the trip to five rafts and six guides.',
      'Shuttle seats are reserved for the whole group.',
      'Waiver links go out and completion is tracked before arrival.',
      'Guides open their assigned raft and passenger list on a phone.',
    ],
    featureSections: [
      {
        heading: 'Group bookings across every channel',
        body: 'Individual and large group bookings land in the same trip capacity, whether they come from your website, a phone call, or an agent. A group that books online is on the trip roster immediately.',
        points: [
          'Booking widget for scheduled departures and private group trips with a deposit or full payment',
          'Group-friendly checkout with headcount, group notes, and add-ons',
          'Agent, DMO, and partner bookings recorded with commission tracking',
          'Front-desk POS for walk-ups, photos, and retail on one ticket',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'Guides, boats, and shuttles planned together',
        body: 'The trip plan reserves every resource the headcount needs at once and holds you to the ratios. Guides pick up their raft and passenger list on a phone.',
        points: [
          'Raft and guide counts driven by headcount and your guide-to-client ratio',
          'Shuttle vehicles attached to a trip with seat capacity enforced, so transport is never overbooked',
          'Guide assignment by qualification, so only cleared guides are scheduled to a river section',
          'Water-level and condition notes on the departure for the day\'s call',
          'Meeting points, map links, and safety notes shared consistently on every confirmation',
        ],
      },
      {
        heading: 'Forms and admin on autopilot',
        body: 'Every participant signs before they arrive, and money-affecting changes leave a clean trail.',
        points: [
          'Per-participant digital waivers with typed e-signature and conditional health or swimmer questions — built in',
          'Waiver status tracked on the booking, so the desk sees who still needs to sign',
          'Automated confirmations and pre-arrival instructions with meeting point and kit list',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the day and can reschedule a departure or reassign a guide, with a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Book 24/7', detail: 'A group of 30 books a half-day rafting trip online and pays a deposit.' },
      { title: 'Size the trip', detail: 'The booking reserves the rafts and guides the headcount needs at your ratio, plus shuttle seats for everyone.' },
      { title: 'Collect waivers', detail: 'Waiver links go to every participant; the desk sees who has signed and who is outstanding.' },
      { title: 'Take payment', detail: 'The balance is scheduled and settled through your own gateway, on one ticket.' },
      { title: 'Run the departure', detail: 'Guides get their assigned raft and passenger list; the shuttle manifest matches the headcount.' },
      { title: 'Close the day', detail: 'Attendance, extras, and the day\'s takings land in reporting.' },
    ],
    outcomes: [
      { label: 'No trip runs short', detail: 'Rafts, guides, and shuttle seats are all reserved from the same headcount, at the ratio you set.' },
      { label: 'Everyone has signed', detail: 'Waiver status per participant sits on the booking, so nobody boards unsigned.' },
      { label: 'Shuttles never overbook', detail: 'Vehicle seat capacity is enforced when transport is attached to a trip.' },
      { label: 'Guides work from a phone', detail: 'Assigned boats and passenger lists are in the field, not on a clipboard in the office.' },
    ],
    constraints: [
      'Water levels and flow rates for the day\'s call',
      'Guide-to-client ratios that vary by river section and activity',
      'Guide qualification per section or activity',
      'Shuttle vehicle seat capacity',
      'Waiver completion for every participant before departure',
    ],
    faqs: [
      { question: 'How are digital waivers handled?', answer: 'Waivers are sent automatically when a booking is made and signed per participant. Their status is tracked on the booking, so the desk can see who still needs to sign before the trip.' },
      { question: 'Can we manage shuttle transport?', answer: 'Yes. Attach a vehicle to a trip and its seat capacity is enforced, so you cannot commit more passengers to a shuttle run than it can carry.' },
      { question: 'Does it handle large corporate groups?', answer: 'Yes. A group books once and the system sizes the rafts, guides, and shuttle seats from the headcount, keeping your guide-to-client ratio.' },
      { question: 'Can it stop an unqualified guide being scheduled?', answer: 'Guides are assigned by qualification, so only those cleared for a river section or activity can be scheduled to it.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'What happens when a group changes its numbers?', answer: 'Adjust the booking and the resource requirements update. A change to a paid order creates a credit note rather than overwriting it.' },
      { question: 'Can guides get the run sheet in the field?', answer: 'Yes. Assigned rafts, passenger lists, and participant notes are on mobile, so guides brief from a phone rather than a clipboard.' },
      { question: 'What can we collect on the per-participant forms?', answer: 'A waiver with a typed e-signature plus conditional health, swimmer, emergency-contact, and custom questions — each participant completes their own.' },
    ],
  },
  {
    id: 'ski-schools',
    name: 'Ski Schools',
    slug: 'ski-schools',
    heroHeadline: 'Handle peak season from the first call to the last run.',
    heroDescription: 'Generic tools do not handle ski and snowboard lessons, multi-day courses, meeting points, and constant last-minute changes. RidgeHQ brings bookings, scheduling, payments, and admin into one flow.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Instructor match by level and language',
      'Built for the 8:45 morning rush',
    ],
    painPoint: 'Ski school demand arrives in a wall at 8:45 a.m.: families wanting privates and group classes at different levels, in different languages, all for the same slot. Matching every booking to the right instructor by hand, at that speed, is where the mistakes happen.',
    keyCapability: 'Every booking carries the student\'s level and language, and instructors are tagged by certification and language — so assignment for the morning rush is a filtered match, not a guessing game.',
    representativeFlow: [
      'A family books private lessons and group classes for children at different levels.',
      'RidgeHQ flags any missing ability levels and requests them.',
      'Instructors are matched by certification level and language.',
      'Morning meeting points go out automatically before the lesson.',
      'End-of-week progress and awards are logged per child.',
    ],
    featureSections: [
      {
        heading: 'Peak-season volume across every channel',
        body: 'Website bookings, front-desk sales, and week-long course packages all draw from the same class capacity, so a group class that fills online is full at the desk before the queue reaches it.',
        points: [
          'Booking widget for privates, group classes, and multi-day courses with a deposit or full payment',
          'Front-desk POS built for rapid booking and assignment during the morning rush',
          'Week-long courses that block the instructor and hold a place in the class for the whole week',
          'Hotel, concierge, and tour-operator referrals recorded with tracked commissions',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'The right instructor, matched fast',
        body: 'Each booking records the student\'s ability level; each instructor is tagged with certifications and languages. Assignment filters to the instructors who actually fit, and flags a booking that is missing its level.',
        points: [
          'Instructor assignment filtered by certification level (beginner, all-mountain, off-piste) and language',
          'Ability level requested on the booking and flagged when it is missing',
          'Morning and afternoon scheduling blocks kept separate, so a slot is never sold twice',
          'Session language tagged so bookings and instructors are matched on it',
          'Meeting points set per booking and included in confirmation and reminder messages',
        ],
      },
      {
        heading: 'The week runs itself',
        body: 'Meeting points, waivers, and end-of-week progress travel with the booking, and money-affecting changes leave a clean trail.',
        points: [
          'Automated meeting-point and start-time messages each morning',
          'Per-participant digital waivers with typed e-signature, conditional health questions, and guardian consent for minors — built in',
          'Progress and end-of-week awards logged per student',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the day and can reschedule a lesson or reassign an instructor, with a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Book and pay 24/7', detail: 'A family books privates and group classes for children at different levels and pays a deposit.' },
      { title: 'Capture the levels', detail: 'The system requests any missing ability levels so every child can be placed correctly.' },
      { title: 'Assign instructors', detail: 'Instructors are matched by certification level and language, keeping morning and afternoon blocks separate.' },
      { title: 'Collect the waiver', detail: 'Each participant signs the waiver and health questions before the first lesson.' },
      { title: 'Send the morning info', detail: 'Meeting point and start time go out automatically; the desk handles walk-ins on the same screen.' },
      { title: 'Close the week', detail: 'Progress and awards are logged per student, and the week\'s totals land in reporting.' },
    ],
    outcomes: [
      { label: 'The 8:45 rush is manageable', detail: 'Bookings arrive pre-tagged with level and language, so assignment is a filter, not a scramble.' },
      { label: 'Right instructor, first time', detail: 'Certification and language matching cuts the mid-morning reshuffles.' },
      { label: 'Slots sell once', detail: 'Separate morning and afternoon blocks stop the same instructor hour being sold twice.' },
      { label: 'One picture of the season', detail: 'Bookings, instructors, and payments move together.' },
    ],
    constraints: [
      'Instructor certification levels (beginner, all-mountain, off-piste)',
      'Instructor and session language',
      'Separate morning and afternoon scheduling blocks',
      'Group class size and ratio limits',
      'Student ability level captured before assignment',
    ],
    faqs: [
      { question: 'Can we filter instructors by language?', answer: 'Yes. Instructors are tagged with languages and certifications, and sessions carry a language, so bookings and instructors are matched on both.' },
      { question: 'Does it handle the morning walk-in rush?', answer: 'Yes. The POS is built for fast booking and assignment, so desk staff can place walk-ins during the rush without leaving the screen.' },
      { question: 'What if a booking is missing the student\'s level?', answer: 'The booking is flagged and the level is requested, so nobody is assigned to a class that does not fit them.' },
      { question: 'Can it manage week-long courses?', answer: 'Yes. A multi-day course blocks the instructor and holds the student\'s place in the class for the whole week.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'What happens when a family changes its lessons mid-week?', answer: 'Adjust the booking and the schedule updates. A change to a paid order creates a credit note rather than overwriting it.' },
      { question: 'Can we manage multiple meeting points and include them in messages?', answer: 'Yes. A meeting point is set per booking and included automatically in the confirmation and the morning reminder.' },
      { question: 'Does it produce an end-of-day close and reporting?', answer: 'Yes. The cash desk closes with reconciled totals, and you can report bookings, cancellations, and revenue by instructor, product, or period with exports.' },
    ],
  },
  {
    id: 'dive-resorts',
    name: 'Dive Resorts',
    slug: 'dive-resorts',
    heroHeadline: 'A hotel and a dive centre, running as one.',
    heroDescription: 'RidgeHQ brings website sales, on-site POS, boat operations, guest paperwork, and the daily close into one system — purpose-built for dive operations and flexible for resort stays with add-ons.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Rooms and dive operations on one system',
      'Package dives drawn down as they are used',
    ],
    painPoint: 'A dive resort runs a hotel and a dive centre at once. When the beds live in one system and the boats in another, package dives get miscounted, a guest gets billed twice, and reception and the dive desk spend the week reconciling by hand.',
    keyCapability: 'Accommodation and the dive schedule share one system and one guest folio — a Stay & Dive package books the room and credits the dives, and each day on the boat draws the package down automatically.',
    representativeFlow: [
      'A guest books a seven-night Stay & Dive package.',
      'A room is held for the stay in the accommodation calendar.',
      'The package\'s dives are credited to the guest\'s profile.',
      'Each dive day draws one dive down from the package.',
      'At checkout, room, dives, and extras settle on a single invoice.',
    ],
    featureSections: [
      {
        heading: 'Sell packages across every channel',
        body: 'Stay & Dive packages, room-only stays, and day-guest dives all book through the same widget and land on the same calendar, so reception and the dive desk see one version of the week.',
        points: [
          'Booking widget for accommodation, dive packages, and courses with a deposit or full payment',
          'Package definitions that reserve the room and credit a set number of dives in one step',
          'Day guests booked onto the same boats as resort guests, capacity permitting',
          'Promo codes applied to the charged total, and agent bookings tracked with commission',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'Rooms and dive days, planned together',
        body: 'The accommodation calendar and the dive schedule sit in the same system. Package dives count down as they are used, and the boat plan shows resort guests and day guests together.',
        points: [
          'Accommodation inventory with availability and turnaround blocks, including shared vs private occupancy',
          'Package dive balance drawn down per guest as each day is logged',
          'Boat manifests built from the day plan with capacity, weights, and assigned crew',
          'Rental gear sizing pulled from each diver\'s profile onto the check-in list',
          'Tide, visibility, and water-temperature context on each dive session',
        ],
      },
      {
        heading: 'One folio, clean books',
        body: 'Everything a guest spends lands on one folio, and money-affecting changes leave a clean trail.',
        points: [
          'Room, dives, rentals, and retail settled on a single guest folio at checkout',
          'Per-participant digital waivers with typed e-signature and conditional medical questions — built in',
          'Course completion recorded per diver, producing the record your agency paperwork needs',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the day and can reschedule a dive or move a diver between boats, with a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Book the package', detail: 'A guest books a seven-night Stay & Dive package online and pays a deposit.' },
      { title: 'Hold room and dives', detail: 'A room is held for the stay and the package\'s dives are credited to the guest\'s profile.' },
      { title: 'Collect the waiver', detail: 'The guest signs the liability waiver and conditional medical questions before the first dive.' },
      { title: 'Dive each day', detail: 'The guest is added to a boat; the dive is logged and one dive is drawn down from the package.' },
      { title: 'Post the extras', detail: 'Nitrox, rentals, courses, and the bar tab are posted to the same folio through the week.' },
      { title: 'Check out', detail: 'Room, dives, and extras settle on a single invoice, and the numbers land in reporting.' },
    ],
    outcomes: [
      { label: 'No more double billing', detail: 'One folio per guest means the room, the dives, and the bar tab reconcile themselves.' },
      { label: 'Package dives always add up', detail: 'Each day on the boat draws the package down, so the count is right at checkout.' },
      { label: 'Reception and dive desk agree', detail: 'Beds and boats share one calendar instead of two systems that drift apart.' },
      { label: 'One picture of the operation', detail: 'Accommodation, dive schedule, gear, and payments move together.' },
    ],
    constraints: [
      'Room availability, occupancy type, and turnaround times',
      'Package inclusion limits (dives included, nitrox, equipment)',
      'Boat and guide capacity shared between resort guests and day guests',
      'Certification and medical clearance per dive or course',
      'Tide, visibility, and water temperature for each site',
    ],
    faqs: [
      { question: 'Can we bill everything to one folio?', answer: 'Yes. Dives, courses, rentals, retail, and the bar tab all post to the guest\'s folio and settle on a single invoice at checkout.' },
      { question: 'How are package dives tracked?', answer: 'A package credits a set number of dives to the guest\'s profile, and each logged dive day draws one down, so the balance is always current.' },
      { question: 'Can day guests dive with resort guests?', answer: 'Yes. Day guests book onto the same boats as resort guests, up to the vessel\'s capacity and crew limits.' },
      { question: 'Does it manage accommodation turnaround?', answer: 'Yes. The accommodation calendar handles availability, occupancy type, and turnaround blocks alongside the dive schedule.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'What happens if a guest shortens their stay?', answer: 'Adjust the booking and the room and dive credits update. A change to a paid order creates a credit note rather than overwriting it.' },
      { question: 'Can we sell rooms with shared and private occupancy?', answer: 'Yes. Accommodation inventory covers shared dorm beds and whole private rooms, linked to the guest\'s dive activities on the same calendar.' },
      { question: 'Can we take a deposit now and the balance during the stay?', answer: 'Yes. Take a deposit at booking and collect the balance or extras later; every charge posts to the same guest folio.' },
    ],
  },
  {
    id: 'surf-camps',
    name: 'Surf Camps',
    slug: 'surf-camps',
    heroHeadline: 'From packages to daily schedules, one flow.',
    heroDescription: 'Beds, meals, daily lessons, and guest prep kept together. RidgeHQ sells week stays with add-ons, collects deposits, captures every guest detail up front, and runs daily rosters without spreadsheets.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Beds, lessons, and transfers on one system',
      'One package sets the whole guest itinerary',
    ],
    painPoint: 'A surf camp week has a lot of moving parts per guest: a bed, an airport pickup, a lesson group at their level, and a note for the kitchen. Run that on a booking tool plus three spreadsheets and every changeover day is a fire drill.',
    keyCapability: 'One weekly package books the bed, adds the guest to the arrival transfer, places them in the right surf group, and captures dietary needs — so the changeover list builds itself.',
    representativeFlow: [
      'A guest books a one-week camp package with airport transfer.',
      'RidgeHQ adds them to the arrival transfer manifest.',
      'A bed in the shared dorm is assigned.',
      'They are placed in the morning beginner group for the week.',
      'Dietary requirements are flagged for the kitchen.',
    ],
    featureSections: [
      {
        heading: 'Sell the week across every channel',
        body: 'Weekly and multi-week packages, add-on nights, and extra lessons all book through one widget and land on one calendar, so the whole camp itinerary comes from a single booking.',
        points: [
          'Booking widget for camp packages, private rooms, and shared dorm beds with a deposit or full payment',
          'Package definitions that bundle bed, board, lessons, and transfer into one product',
          'Add-ons — extra lessons, rental boards, video coaching, yoga — on the same booking',
          'Custom fields at checkout for flight times, dietary needs, sizes, and experience',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'Hospitality and surf, planned together',
        body: 'Beds, transfers, and lesson groups share one system. A booking places the guest everywhere it needs to at once, and the changeover view shows arrivals, departures, and bed moves for the day.',
        points: [
          'Accommodation by the bed in shared dorms as well as private rooms',
          'Arrival and departure transfer manifests sized against vehicle seat capacity',
          'Guests placed in a surf group by level, with instructor ratios enforced',
          'Tide and swell context on lesson sessions from your spot\'s forecast',
          'Rental boards and wetsuits reserved for the week from the shared fleet',
        ],
      },
      {
        heading: 'The week runs itself',
        body: 'Kitchen notes, waivers, and pre-arrival information travel with the booking, and money-affecting changes leave a clean trail.',
        points: [
          'Dietary and allergy requirements captured on the booking and reportable for the kitchen',
          'Per-participant digital waivers with typed e-signature and conditional health questions — built in',
          'Automated pre-arrival emails with travel details, packing list, and schedule',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the week and can reschedule a lesson or reassign an instructor, with a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Book the package', detail: 'A guest books a one-week camp package with airport transfer and pays a deposit.' },
      { title: 'Build the itinerary', detail: 'The package assigns a bed, adds the guest to the arrival transfer, and books their week of lessons.' },
      { title: 'Place and flag', detail: 'The guest is placed in a surf group by level; dietary needs are flagged for the kitchen.' },
      { title: 'Collect the waiver', detail: 'Each guest signs the waiver and health questions before the first session.' },
      { title: 'Run the changeover', detail: 'The changeover view shows arrivals, departures, transfer manifests, and bed moves in one place.' },
      { title: 'Close the week', detail: 'Extras are settled, progress is logged, and the week\'s totals land in reporting.' },
    ],
    outcomes: [
      { label: 'Changeover stops being a fire drill', detail: 'Arrivals, departures, transfers, and bed moves come off one list built from the bookings.' },
      { label: 'One booking sets the whole week', detail: 'Bed, board, lessons, and transfer are placed together, not entered four times.' },
      { label: 'The kitchen gets clean numbers', detail: 'Dietary and allergy needs are reportable per week instead of scattered across emails.' },
      { label: 'One picture of the operation', detail: 'Beds, transfers, lessons, and payments move together.' },
    ],
    constraints: [
      'Bed and room capacity across dorms and private rooms',
      'Instructor ratios for the included lessons',
      'Transfer vehicle seat capacity for arrivals and departures',
      'Tide and swell suitability for each group\'s level',
      'Rental board and wetsuit stock reserved for the week',
    ],
    faqs: [
      { question: 'Can we manage shared dorms?', answer: 'Yes. You can sell and assign by the bed in shared dormitories as well as booking whole private rooms.' },
      { question: 'Can we track dietary requirements?', answer: 'Yes. Dietary and allergy needs are captured on the booking and can be reported per week for the kitchen.' },
      { question: 'How are airport transfers handled?', answer: 'Guests are added to arrival and departure manifests sized against the vehicle\'s seat capacity, so a transfer run is never overbooked.' },
      { question: 'Can a package bundle bed, lessons, and transfer?', answer: 'Yes. A package product bundles accommodation, the week of lessons, board hire, and the transfer, so one booking sets the whole itinerary.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'What happens when a guest changes their dates?', answer: 'Adjust the booking and the bed, transfer, and lessons update. A change to a paid order creates a credit note rather than overwriting it.' },
      { question: 'Can staff access the daily schedule on mobile?', answer: 'Yes. Instructors and hosts see the day\'s groups, arrivals, and notes on a phone, kept current through the week.' },
      { question: 'Can we sell extras like coaching or rentals on the same booking?', answer: 'Yes. Add-ons attach to the camp booking, so the guest\'s whole week — and its price — sits on one order.' },
    ],
  },
  {
    id: 'kayak-rental-tours',
    name: 'Kayak Rental & Tours',
    slug: 'kayak-rental-tours',
    heroHeadline: 'Run your kayak and paddle operation at full speed.',
    heroDescription: 'One booking and operations system for kayak and SUP rentals and guided tours. Availability, payments, customer details, and the daily run stay unified from the front desk to the dock.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'One inventory for tours and walk-in hire',
      'Guides scheduled at the ratio you set',
    ],
    painPoint: 'A kayak operation sells guided tours and hires boats by the hour from the same rack. Without one shared inventory, a tour turns up needing ten doubles that walked out the door an hour earlier, and the desk finds out at the water.',
    keyCapability: 'Tours and walk-in hire draw from one boat inventory, so a kayak reserved for the 6 p.m. tour is not on the walk-in rack at 5 — and guides are scheduled against the tour headcount at your ratio.',
    representativeFlow: [
      'A group books a guided sunset tour online.',
      'RidgeHQ reserves ten doubles and assigns a guide.',
      'A walk-in asks for two singles for an hour.',
      'The POS only offers singles not needed for the upcoming tour.',
      'Waivers are signed per participant on a device at the desk.',
    ],
    featureSections: [
      {
        heading: 'Tours and hire from one system',
        body: 'Scheduled tours booked online and walk-in hire at the desk draw from the same boat inventory, so committed stock is never offered twice.',
        points: [
          'Booking widget for guided tours and pre-booked hire with a deposit or full payment',
          'Front-desk POS for walk-in hire, retail, and add-ons on one ticket',
          'Return times tracked per boat, with an overdue flag at the desk',
          'Seasonal pricing rules, add-on extras, and promo codes on the same products',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'Fleet-smart scheduling for the daily run',
        body: 'Every boat shows its status, and stock reserved for an upcoming tour is held back from walk-in hire automatically.',
        points: [
          'Single and double kayaks tracked as separate stock with live availability',
          'Boats reserved for a scheduled tour removed from the walk-in pool for that window',
          'Add-ons — PFDs, paddles, dry bags, wetsuits — tracked against each hire',
          'Turnaround time between a return and the next hire built into availability',
          'Guides scheduled against the tour headcount at your guide-to-client ratio',
        ],
      },
      {
        heading: 'Forms and books stay clean',
        body: 'Waivers and confirmations travel with the booking, and money-affecting changes leave a clean trail.',
        points: [
          'Per-participant digital waivers with typed e-signature and conditional health or swimmer questions — built in',
          'Waiver status tracked on the booking, so the desk sees who still needs to sign',
          'Automated confirmations and pre-tour instructions with meeting point and kit',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the day and can reschedule a tour or reassign a guide, with a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Book the tour', detail: 'A group books a guided sunset tour online and pays a deposit.' },
      { title: 'Reserve the boats', detail: 'The tour reserves the doubles it needs and assigns a guide at your ratio.' },
      { title: 'Take the walk-in', detail: 'A walk-in asks for singles for an hour; the POS only offers boats not needed for the upcoming tour.' },
      { title: 'Collect waivers', detail: 'Every participant signs on a device at the desk; the booking shows who is outstanding.' },
      { title: 'Send it out', detail: 'Boats are marked out with return times; the desk sees an overdue flag if a hire runs late.' },
      { title: 'Close the day', detail: 'Returns, damage notes, and the day\'s takings land in reporting.' },
    ],
    outcomes: [
      { label: 'Tours never come up short', detail: 'Boats reserved for a departure are held back from walk-in hire for that window.' },
      { label: 'You know what is on the water', detail: 'Every kayak shows available, out, due back, or in for repair.' },
      { label: 'Guides scheduled to the ratio', detail: 'Guide numbers come off the tour headcount, not a mental estimate.' },
      { label: 'One ticket per customer', detail: 'Tours, hire, and retail settle together instead of across separate systems.' },
    ],
    constraints: [
      'Separate stock of single vs double kayaks',
      'Turnaround time for cleaning and checking boats between hires',
      'Guide availability and guide-to-client ratios per tour',
      'Return times and overdue tracking for boats on the water',
      'Waiver completion for every participant before launch',
    ],
    faqs: [
      { question: 'Does it prevent double-booking gear?', answer: 'Yes. Boats assigned to a scheduled tour are removed from the walk-in pool for that window, so the same kayak cannot be hired out from under a departure.' },
      { question: 'How are waivers handled for walk-ins?', answer: 'Waivers are signed per participant on a device at the desk, with a typed e-signature. The booking shows who has signed and who is still outstanding.' },
      { question: 'Can it track single and double kayaks separately?', answer: 'Yes. Each is its own stock with live availability, so a tour needing doubles does not draw down your singles.' },
      { question: 'Does it handle guide ratios?', answer: 'Yes. Guides are scheduled against the tour headcount at the guide-to-client ratio you set.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'What happens when a tour group changes numbers?', answer: 'Adjust the booking and the boats and guides update. A change to a paid order creates a credit note rather than overwriting it.' },
      { question: 'Can we set seasonal pricing and sell add-ons?', answer: 'Yes. Products carry seasonal pricing rules, add-on extras like dry bags and wetsuits, and promo codes applied to the charged total.' },
      { question: 'Can dock staff work from a phone?', answer: 'Yes. The live schedule and booking details are on mobile, so the dock is not waiting on a printed list or a call to the desk.' },
    ],
  },
  {
    id: 'bike-rental-tours',
    name: 'Bike Rental & Tours',
    slug: 'bike-rental-tours',
    heroHeadline: 'Run your bike rental shop at full speed.',
    heroDescription: 'Stop managing rentals across paper, chat apps, and spreadsheets. RidgeHQ puts rentals, fleet availability, payments, and staff scheduling on one live calendar — for the shop floor and guided tours.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Every bike tracked as its own asset',
      'Size and service state drive availability',
    ],
    painPoint: 'A bike fleet is not interchangeable stock — it is individual assets, each with a frame size, a service history, and a battery that needs turnaround time. Booking "an e-bike" and sorting out which one on the morning of pickup is how you hand over a bike with a flagged brake.',
    keyCapability: 'Every bike is its own tracked asset with a size and a service state, so a booking reserves a specific frame in the right size and a bike flagged for repair is simply not offered.',
    representativeFlow: [
      'A customer books an e-MTB rental for three days.',
      'RidgeHQ reserves a specific size Large bike.',
      'On return, the mechanic logs a brake issue.',
      'That bike is marked out of service and removed from availability.',
      'Once repaired, it is released back into the fleet.',
    ],
    featureSections: [
      {
        heading: 'Rentals and tours from one system',
        body: 'Online rentals, walk-in hire, and guided tours all draw from the same fleet, so a bike committed to Saturday\'s tour is not double-booked to a three-day rental.',
        points: [
          'Booking widget for rentals and guided tours with a deposit or full payment',
          'Multi-day, half-day, and seasonal pricing rules on the same products',
          'Front-desk POS for walk-in hire, rental extensions, accessories, and retail on one ticket',
          'Partner and hotel referrals recorded with limited access and tracked commission',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'Asset-level fleet management',
        body: 'Each bike carries its type, frame size, and service record. Availability reflects the real state of each unit, not a generic count.',
        points: [
          'Bookings reserve a specific bike by type and frame size (S / M / L / XL)',
          'Service history and safety checks logged per bike',
          'A bike flagged out of service is removed from availability until it is checked back in',
          'Turnaround time between a return and the next hire built into availability',
          'Guided tours reserve specific bikes and assign a guide at your ratio',
        ],
      },
      {
        heading: 'Forms and books stay clean',
        body: 'Waivers and confirmations travel with the booking, and money-affecting changes leave a clean trail.',
        points: [
          'Per-participant digital waivers with typed e-signature and conditional health questions — built in',
          'Automated confirmations and pickup instructions with the reserved bike and size',
          'Security deposits pre-authorised through supported gateways and released after inspection',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the day and can reschedule a tour or reassign a guide, with a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Book online', detail: 'A customer books an e-MTB for three days online, chooses a frame size, and pays a deposit.' },
      { title: 'Reserve the bike', detail: 'A specific size Large e-MTB is held for the dates; multi-day pricing is applied automatically.' },
      { title: 'Waiver and deposit', detail: 'The customer signs the waiver and a security deposit is pre-authorised through your gateway.' },
      { title: 'Hand it over', detail: 'The reserved bike is handed over; the customer confirms its condition on the booking.' },
      { title: 'Check it back in', detail: 'The mechanic checks the bike in; any issue is logged and the bike is flagged out of service if needed.' },
      { title: 'Settle', detail: 'The deposit is released after inspection and the day\'s totals land in reporting.' },
    ],
    outcomes: [
      { label: 'No surprise bikes at pickup', detail: 'A specific frame in the right size is reserved at booking, not chosen in the morning scramble.' },
      { label: 'Flagged bikes stay in the workshop', detail: 'An out-of-service bike is off availability until it is checked back in.' },
      { label: 'Rentals and tours do not collide', detail: 'One fleet, so a bike on Saturday\'s tour is not also on a weekend rental.' },
      { label: 'Deposits handled cleanly', detail: 'Pre-authorised at booking, released after inspection, all on the same order.' },
    ],
    constraints: [
      'Frame size matching (S / M / L / XL) per booking',
      'Battery and cleaning turnaround time between hires',
      'Service history and safety checks per bike',
      'Shared fleet across rentals, walk-in hire, and guided tours',
      'Security deposit pre-authorisation and release',
    ],
    faqs: [
      { question: 'Can we track maintenance per bike?', answer: 'Yes. Service history and safety checks are logged per bike, and flagging one out of service removes it from availability immediately.' },
      { question: 'Does it handle multi-day and seasonal pricing?', answer: 'Yes. Products support multi-day rules, half-days, and seasonal pricing, applied automatically at booking.' },
      { question: 'Can it reserve a specific frame size?', answer: 'Yes. Bookings reserve a specific bike by type and frame size, so the right bike is set aside before the customer arrives.' },
      { question: 'How are security deposits handled?', answer: 'With supported payment gateways, a deposit is pre-authorised at booking and released after the post-rental inspection.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'What happens if a rental is cut short or extended?', answer: 'Adjust the booking and pricing and availability update. A change to a paid order creates a credit note rather than overwriting it.' },
      { question: 'Can we handle rental extensions at the counter?', answer: 'Yes. Extend a live hire on the POS; pricing and availability update, and the change is a credit note against the original order rather than a rewrite.' },
      { question: 'Do we get fleet utilisation and sales reporting?', answer: 'Yes. Reporting covers per-bike utilisation, sales by product and period, and a daily close with exports for accounting.' },
    ],
  },
  {
    id: 'boat-rental-courses',
    name: 'Boat Rental & Courses',
    slug: 'boat-rental-courses',
    heroHeadline: 'Run charters and skipper courses at full speed.',
    heroDescription: 'Stop juggling boat availability, course sessions, payments, and paperwork. RidgeHQ keeps charters and training in one place so you fill more dates, avoid double-bookings, and run smoother at the dock.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Licence and ID checked before the charter',
      'Deposits pre-authorised and released cleanly',
    ],
    painPoint: 'Handing over a boat worth six figures depends on two things going right: the right licence on file for a bareboat charter, and a security deposit that is actually held. Chase both by email and one of them slips — the client arrives without the paperwork, or the deposit was never taken.',
    keyCapability: 'The booking collects the licence and ID up front for staff to verify, pre-authorises the deposit through your gateway, and holds the specific vessel — so nothing is handed over until the checks clear.',
    representativeFlow: [
      'A client books a bareboat charter online.',
      'RidgeHQ prompts them to upload their licence and ID.',
      'Staff verify the documents before the arrival day.',
      'A security deposit is pre-authorised through the gateway.',
      'After the post-charter inspection, the deposit is released.',
    ],
    featureSections: [
      {
        heading: 'Charters and courses from one calendar',
        body: 'Bareboat and skippered charters and taught powerboat courses draw from the same fleet availability, so a boat out on a course is not offered for a weekend charter.',
        points: [
          'Booking widget for charters and certification courses with a deposit or full payment',
          'Bareboat, skippered, and instruction bookings managed on the same vessels',
          'Front-desk POS for fuel, provisioning, and extras on one ticket',
          'Agent bookings recorded with synced availability and commission where used',
          '0% platform commission on direct bookings',
        ],
      },
      {
        heading: 'Checks before the keys',
        body: 'Document collection, verification, and the deposit are part of the booking flow, and the vessel\'s own compliance dates are tracked.',
        points: [
          'Licence and ID uploaded by the client before arrival for staff to verify',
          'Booking held in an unverified state until the documents are cleared',
          'Security deposit pre-authorised through supported gateways and released after inspection',
          'Vessel records with capacity, registration, and inspection / licence / insurance expiry tracking',
          'Skipper and examiner assignment per vessel for skippered charters and courses',
        ],
      },
      {
        heading: 'Handover and books stay clean',
        body: 'Waivers, condition records, and confirmations travel with the booking, and money-affecting changes leave a clean trail.',
        points: [
          'Per-participant digital waivers with typed e-signature and conditional experience questions — built in',
          'Pre-departure condition notes and post-charter inspection recorded against the booking',
          'Automated confirmations and joining instructions with berth and check-in time',
          'Order immutability: an edit to a paid order creates a credit note, not a silent rewrite',
          'An AI copilot that reads the schedule and can reschedule a charter or reassign a skipper, with a confirm step',
        ],
      },
    ],
    workflow: [
      { title: 'Book the charter', detail: 'A client books a bareboat charter online and pays a deposit toward the fee.' },
      { title: 'Upload documents', detail: 'The client uploads their licence and ID; the booking stays unverified until staff clear them.' },
      { title: 'Hold the deposit', detail: 'A security deposit is pre-authorised through your gateway ahead of the arrival day.' },
      { title: 'Hand over the boat', detail: 'With checks cleared, the specific vessel is handed over and pre-departure condition is recorded.' },
      { title: 'Inspect on return', detail: 'The post-charter inspection is logged against the booking and any damage noted.' },
      { title: 'Settle', detail: 'The deposit is released after inspection and the numbers land in reporting.' },
    ],
    outcomes: [
      { label: 'No handover without the paperwork', detail: 'The booking stays unverified until the licence and ID are checked.' },
      { label: 'Deposits are actually held', detail: 'Pre-authorised at booking and released after inspection, on the same order.' },
      { label: 'Charters and courses do not clash', detail: 'One fleet calendar, so a boat on a course is not chartered the same dates.' },
      { label: 'Compliance dates in view', detail: 'Inspection, licence, and insurance expiry are tracked on the vessel.' },
    ],
    constraints: [
      'Vessel availability and turnaround time between bookings',
      'Client licence and ID verification status',
      'Skipper and instructor availability for skippered work',
      'Inspection, licence, and insurance expiry per vessel',
      'Security deposit pre-authorisation and release',
    ],
    faqs: [
      { question: 'Can clients upload documents before arriving?', answer: 'Yes. The client uploads their licence and ID with the booking, and it stays unverified until your staff have checked them.' },
      { question: 'How are security deposits handled?', answer: 'With supported payment gateways, the deposit is pre-authorised at booking and released after the post-charter inspection.' },
      { question: 'Can we run charters and courses on the same boats?', answer: 'Yes. Bareboat, skippered, and instruction bookings draw from the same fleet availability, so the two cannot book a vessel for overlapping dates.' },
      { question: 'Does it track vessel compliance?', answer: 'Each vessel records its registration and its inspection, licence, and insurance expiry dates, and is flagged as those dates approach.' },
      { question: 'Do you issue the certification?', answer: 'No. RidgeHQ manages the training operation — scheduling, sessions, and records — while the certificate itself is issued by your certifying body.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own site carry 0% platform commission — you pay your normal gateway fee and a flat monthly subscription.' },
      { question: 'Can we sell fuel, provisioning, and extras at check-out?', answer: 'Yes. Extras go on the same order at the front desk, and the security deposit is released after the post-charter inspection.' },
      { question: 'Can we schedule instructors and examiners against boat availability?', answer: 'Yes. Skippers and examiners are assigned per vessel, so a session cannot confirm without both the boat and a cleared person free.' },
    ],
  },
];
