export interface VerticalFeatureSection {
  heading: string;
  body: string;
  points: string[];
}

export interface VerticalWorkflowStep {
  title: string;
  detail: string;
}

export interface VerticalOutcome {
  label: string;
  detail: string;
}

export interface Vertical {
  id: string;
  name: string;
  slug: string;
  /** ISO date — bump when this vertical's content is meaningfully updated. Used as the sitemap <lastmod>. */
  lastUpdated: string;
  /** The buyer search phrase this page targets (from Search Console queries). Shown as the hero eyebrow. */
  searchKeyword: string;
  /** Page <title>, leading with searchKeyword. The site template appends " | RidgeHQ App". */
  seoTitle: string;
  /** Meta description. Must contain searchKeyword and stay within 160 characters. */
  metaDescription: string;
  heroHeadline: string;
  heroDescription: string;
  painPoint: string;
  keyCapability: string;
  representativeFlow: string[];
  constraints: string[];
  faqs: { question: string; answer: string }[];
  /**
   * Extended marketing content. Added progressively per vertical — the
   * template renders these sections only when the data is present, so a
   * vertical without them still renders the core layout.
   */
  heroProofPoints?: string[];
  featureSections?: VerticalFeatureSection[];
  workflow?: VerticalWorkflowStep[];
  outcomes?: VerticalOutcome[];
  /** src/lib/config/platform.ts slugs this vertical's content most directly draws on. */
  relatedPlatformSlugs: string[];
}

export const verticals: Vertical[] = [
  {
    id: 'dive-centers',
    name: 'Dive Centers',
    slug: 'dive-centers',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Dive center software',
    seoTitle: 'Dive Center Software: Bookings, Boats & Waivers',
    metaDescription: 'Dive center software that runs bookings, boat manifests, kit sizing, and digital waivers from one schedule, with 0% commission on direct bookings.',
    heroHeadline: 'From first click to final dive, on one system.',
    heroDescription: 'Generic booking tools do not understand boats, two-tank days, kit prep, or per-diver medicals. RidgeHQ puts dive-specific rosters, waivers, payments, and multi-channel sales in one place.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Boat manifests generated from the session roster',
      'Per-participant waivers and medical forms, built in',
    ],
    painPoint: 'A typical dive center sells on a booking widget, plans the boat on a whiteboard, keeps kit sizing in a folder, and logs course progress in a spreadsheet. Every course that fills online is re-typed onto the manifest by hand, every gear swap is checked from memory, and no screen shows the whole day at once.',
    keyCapability: 'Every booking lands on the session with the diver\'s certification level and stored kit sizes attached — so the roster, the boat manifest, and the gear prep list are generated from it instead of copied across three tools.',
    relatedPlatformSlugs: ['scheduling', 'gear-rentals', 'customers-participants'],
    representativeFlow: [
      'A diver books an Advanced course online, pays a deposit, and signs the waiver and medical form.',
      'Their certification record and equipment sizes are already on their profile — or captured once now.',
      'An instructor is assigned to the session; an overlapping assignment is refused.',
      'The day\'s boat manifest is generated from the confirmed participants, with certifications and sizes.',
      'When the course ends, the head instructor marks the diver completed and a certification record is created.',
    ],
    featureSections: [
      {
        heading: 'One checkout for the website, the desk, and your agents',
        body: 'Courses, fun dives, and packages sold online, at the counter, or through a hotel agent all write to the same sessions and the same orders. A course that fills on the website is full at the desk a moment later, without anyone re-typing it.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Products can require a minimum certification level; the booking form asks for the diver\'s level and licence number only where it is required',
        ],
      },
      {
        heading: 'Boat days built from real bookings',
        body: 'The planner shows the week by activity, staff, or trip. Boat trips group the sessions that travel together, carry their pilot and destination site, and produce a manifest from the confirmed divers — so the dock list is never a hand-copied version of the booking sheet.',
        points: [
          'Trips with a pilot, destination site, and capacity computed from their sessions',
          'Boat manifest per session: confirmed divers with certification and kit sizes, linked to the vessel',
          'Overlap checks on instructor and pilot assignments',
          'Wind, wave, swell, visibility, water-temperature, and tide context for the dive site',
          'Per-activity thresholds that flag a session when conditions exceed your limits',
          'Trip gear prep list built from each diver\'s sizes and needs, with a packed tick per line',
        ],
      },
      {
        heading: 'The paperwork, kept with the diver',
        body: 'Certifications, waivers, sizing, and dive history live on the diver\'s profile and travel with every booking, so check-in is a confirmation rather than an interview.',
        points: [
          'Certification records with level and the staff member who verified them, from a PADI / SSI / CMAS catalogue',
          'Per-participant waivers with typed signature, a medical questionnaire, and conditional questions',
          'Equipment sizing — wetsuit, BCD, fins, mask, shoe, and weight — stored once',
          'Dive log per diver with site, depth, duration, and automatic dive numbering',
          'Course tracker with attendance; marking a diver completed creates their certification record',
        ],
      },
    ],
    workflow: [
      { title: 'Book 24/7', detail: 'A diver books a course or a two-tank trip on your website, pays a deposit, and answers your waiver and medical questions.' },
      { title: 'Confirm on payment', detail: 'The order confirms once the online payment succeeds; any balance is tracked against the order and settled at the desk.' },
      { title: 'Check qualifications', detail: 'Courses that need a prerequisite ask for the diver\'s level and licence number, and the roster shows it.' },
      { title: 'Plan the boat', detail: 'Sessions are grouped into a trip with a pilot and dive site; instructor and pilot overlaps are refused.' },
      { title: 'Generate the manifest', detail: 'The manifest is generated from the confirmed divers with certifications and kit sizes; the gear prep list comes from the same data.' },
      { title: 'Close the day', detail: 'Dive logs and course completions are recorded, the register closes, and revenue by origin lands in reporting.' },
    ],
    outcomes: [
      { label: 'Sales while the shop is shut', detail: 'The widget sells courses and trips overnight into the same sessions your team plans from.' },
      { label: 'Manifests without re-typing', detail: 'The dock list is generated from confirmed bookings, with certifications and sizes already on it.' },
      { label: 'Faster check-in', detail: 'Waivers, medical answers, and sizes are collected before the diver walks in.' },
      { label: 'Records that add up', detail: 'Course completions create certification records, and paid-order changes produce credit notes.' },
    ],
    constraints: [
      'Boat passenger capacity, weight distribution, and crew assignment',
      'Instructor-to-diver ratios that vary by course and agency standard',
      'Cylinder, weight, and specialty-gear stock (nitrox, drysuit, camera)',
      'Certification prerequisites and medical clearance per course',
      'Tide windows, visibility, and water temperature for each site',
    ],
    faqs: [
      { question: 'What does RidgeHQ replace as dive center software?', answer: 'Usually the booking widget, the whiteboard boat plan, the kit-sizing folder, and the course spreadsheet. Bookings, trips, manifests, waivers, sizing, and payments run from one set of sessions, so a course sold online appears on the manifest without being re-typed.' },
      { question: 'Does it replace my PADI or SSI portal?', answer: 'No. Certifications are still issued through your agency. RidgeHQ is your operational record: it stores each diver\'s certification level and who verified it, tracks course attendance, and creates a certification record when a head instructor marks a course completed.' },
      { question: 'How are boat manifests produced?', answer: 'A manifest is generated for a session from its confirmed participants and includes each diver\'s certification and kit sizes. It is linked to the vessel, so each boat\'s list comes from real bookings.' },
      { question: 'Can we run more than one boat?', answer: 'Yes. Each vessel is a fleet asset with its own capacity, crew, and inspection history, and trips carry their own pilot, destination site, and sessions. A pilot can\'t be put on two overlapping trips.' },
      { question: 'Does RidgeHQ enforce instructor-to-diver ratios?', answer: 'Not automatically today. Each session has its own capacity and the roster shows who is booked and their level, so you can size sessions to your agency\'s standard — but RidgeHQ does not calculate or enforce a ratio for you.' },
      { question: 'How do digital waivers work?', answer: 'Each diver signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'surf-schools',
    name: 'Surf Schools',
    slug: 'surf-schools',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Surf school software',
    seoTitle: 'Surf School Software: Lessons, Rentals & Camps',
    metaDescription: 'Surf school software for private lessons, group classes, and camps, with board and wetsuit rental, student progression, and forecast-aware rescheduling.',
    heroHeadline: 'Fill more classes and keep the whole day in sync.',
    heroDescription: 'Stop juggling spreadsheets, group chats, and last-minute changes. RidgeHQ brings bookings, tide and swell context, instructor planning, rentals, and payments into one system.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Tide and swell context on every session',
      'Move or reschedule a group in one action',
    ],
    painPoint: 'Surf timetables move with the tide and the forecast, and most schools re-plan by hand — messaging instructors, chasing wetsuit sizes, rebooking groups one reply at a time. The booking site, the board rack, and the progression sheet never quite agree.',
    keyCapability: 'Each session carries the tide and swell context for your break next to its roster and board list — so when the forecast turns, you move the group in the planner and email everyone booked on it from the same screen.',
    relatedPlatformSlugs: ['scheduling', 'gear-rentals', 'staff'],
    representativeFlow: [
      'A group books a three-day beginner camp online and pays a deposit.',
      'Each participant signs the waiver and answers your health questions.',
      'Instructors are assigned to each session; double-booking an instructor is refused.',
      'If the swell is outside your beginner thresholds, the session is flagged and you reschedule it.',
      'You email every participant on the session from the planner, and the day closes into reporting.',
    ],
    featureSections: [
      {
        heading: 'Sell lessons, camps, and hire on one availability',
        body: 'Website bookings, front-desk sales, and multi-day camp packages all write to the same session capacity, so a camp that sells out online is full at the desk the moment it happens.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Camp products that bundle accommodation and rental components with optional add-ons',
        ],
      },
      {
        heading: 'Plan around the tide, re-plan in a few clicks',
        body: 'Every session shows the tide and swell forecast for your spot beside the roster. Thresholds you set per activity flag a beginner group when the surf is too big, and the planner lets you move, reschedule, or bulk-update sessions without rebuilding the day.',
        points: [
          'Tide, swell height, swell period, and wind context for the session\'s spot',
          'Per-activity thresholds so a beginner session is flagged when conditions are outside your limits',
          'Optionally stop new bookings for a session when the forecast breaches your thresholds',
          'Move, reschedule, clone, or bulk-update sessions in the weekly planner',
          'Email every confirmed participant of a session from the planner',
        ],
      },
      {
        heading: 'Boards, wetsuits, and paperwork that keep up',
        body: 'Rental gear is tracked by unit and size, and each customer\'s sizes are stored on their profile, so the board rack and the booking sheet agree. Waivers and changes to paid orders are handled on the booking itself.',
        points: [
          'Boards and wetsuits tracked as units with sizes; availability matched size-for-size',
          'Equipment sizes stored on the customer profile and reused',
          'Per-participant waivers with typed signature and conditional health questions',
          'Products can require a minimum skill level, asked for only where it is required',
          'Changes to a paid order create a credit note instead of rewriting it',
        ],
      },
    ],
    workflow: [
      { title: 'Book 24/7', detail: 'A group books a lesson block or camp online, pays a deposit, and answers your experience and health questions.' },
      { title: 'Confirm on payment', detail: 'The order confirms once the online payment succeeds; the balance is tracked against the order.' },
      { title: 'Sign the waiver', detail: 'Each participant signs the waiver before the first session, attached to their booking.' },
      { title: 'Assign instructors', detail: 'Instructors are assigned per session in the planner; overlapping assignments are refused.' },
      { title: 'Check the forecast', detail: 'Sessions outside your tide, swell, or wind thresholds are flagged; you move or reschedule them and email the group.' },
      { title: 'Close the day', detail: 'Hire and walk-ins settle at the register, and revenue by origin lands in reporting.' },
    ],
    outcomes: [
      { label: 'Bookings after hours', detail: 'The widget sells lessons and camps overnight into the same sessions your instructors work from.' },
      { label: 'Forecast next to the plan', detail: 'Tide and swell sit beside the session they affect, against thresholds you set.' },
      { label: 'Kit that matches the booking', detail: 'Size-matched gear availability means the right board and wetsuit are there.' },
      { label: 'Enter a booking once', detail: 'Rosters, waivers, and reporting read from the booking instead of a separate sheet.' },
    ],
    constraints: [
      'Tide windows and safe swell height for each ability level',
      'Wetsuit and board sizing matched to student size and skill',
      'Instructor availability by certification level (for example ISA L1 vs L2) and language',
      'Rental fleet shared between lessons and walk-in hire',
      'Multi-day camp blocks that span several sessions',
    ],
    faqs: [
      { question: 'What makes RidgeHQ surf school software rather than a generic booking tool?', answer: 'It is built around a surf day: each session carries tide and swell context for your break, lessons, group classes, and camps share one calendar, boards and wetsuits are tracked by size, and instructors are checked against overlapping sessions.' },
      { question: 'How does it handle a bad forecast?', answer: 'Sessions show the tide, swell, and wind for your spot, and per-activity thresholds flag sessions outside your limits. You decide: move or reschedule the session in the planner and email the participants from the same screen. You can also opt in to blocking new bookings when the forecast breaches a threshold.' },
      { question: 'Are participants messaged automatically when we reschedule?', answer: 'Not automatically on reschedule. You send the update yourself with the planner\'s session email, which goes to every confirmed participant at once. Cancelling a session does send its own cancellation notice.' },
      { question: 'Can it manage private and group lessons together?', answer: 'Yes. Private sessions, open group classes, and multi-day camps share one calendar, each with its own capacity and assigned instructors.' },
      { question: 'Can we rent boards and wetsuits through the same system?', answer: 'Yes. Rental gear is tracked by unit and size and shares availability with lessons, so gear sold to a walk-in at the counter isn\'t also promised to a class.' },
      { question: 'How do digital waivers work?', answer: 'Each participant signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'kitesurf-schools',
    name: 'Kitesurf Schools',
    slug: 'kitesurf-schools',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Kitesurf school booking system',
    seoTitle: 'Kitesurf School Booking System & Lesson Software',
    metaDescription: 'Kitesurf school booking system: students book lessons online, sessions show the wind forecast against your limits, and kites are tracked by size.',
    heroHeadline: 'Sell more sessions, reschedule fast when the wind shifts.',
    heroDescription: 'Generic tools do not get wind windows, last-minute reshuffles, or multi-session courses. RidgeHQ gives you online sales, wind-aware scheduling, kites tracked by size, and forms that adapt.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Wind speed and direction against your limits',
      'Kites and harnesses tracked by size',
    ],
    painPoint: 'Kite lessons only run inside a wind window, so schools lose the morning to "wind is on" messages and then a hunt for a kite in the right size. The booking tool, the gear board, and the progression cards sit in three places, and none of them read the forecast.',
    keyCapability: 'Sessions show the wind forecast for your spot against minimum, maximum, and direction limits you set — and kites, boards, and harnesses are tracked by size against each student\'s stored weight — so the wind call and the kit call are made from one screen.',
    relatedPlatformSlugs: ['scheduling', 'gear-rentals'],
    representativeFlow: [
      'A student books a beginner course online, gives their weight, and signs the waiver.',
      'The course\'s sessions sit in the planner with the wind forecast for your spot.',
      'Sessions outside your minimum, maximum, or direction limits are flagged.',
      'The instructor picks a kite and harness by size, against the student\'s stored weight.',
      'Confirmed or moved, the group gets an update from the planner\'s session email.',
    ],
    featureSections: [
      {
        heading: 'Sell lessons and courses across every channel',
        body: 'Website bookings, front-desk sales, and hotel or agent referrals all draw from the same sessions, so the team sees a course sold online immediately.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Products can require a minimum skill level; the booking form asks for it only where needed',
        ],
      },
      {
        heading: 'Wind-aware scheduling',
        body: 'Each session shows the forecast wind speed and direction for your spot next to the roster. Thresholds per activity cover both a minimum and a maximum wind and a usable direction range, so a lesson is flagged when it is too light, too strong, or blowing the wrong way.',
        points: [
          'Wind speed, direction, wave, and swell context from your spot\'s forecast',
          'Per-activity minimum and maximum wind, plus a wind-direction range',
          'Optionally stop new bookings for a session when the forecast breaches your limits',
          'Move, reschedule, or bulk-update sessions when the window changes',
          'Email everyone booked on a session from the planner',
        ],
      },
      {
        heading: 'Expensive kit, tracked by unit and size',
        body: 'Kites, boards, harnesses, and radio helmets are tracked as individual units with sizes. Each student\'s weight and sizes live on their profile, so choosing the right kit is a lookup, not a guess — and gear out for repair leaves availability the moment it\'s logged.',
        points: [
          'Kites, boards, harnesses, and helmets tracked as units with sizes',
          'Student weight and sizes stored on the profile',
          'Maintenance records remove gear from availability until it is returned',
          'Safety boats tracked as fleet assets with inspection, licence, and insurance dates',
          'Per-participant waivers with typed signature and conditional health questions',
        ],
      },
    ],
    workflow: [
      { title: 'Book the course', detail: 'A student books online, pays up front or a deposit, and gives their weight and experience.' },
      { title: 'Confirm on payment', detail: 'The order confirms once the payment succeeds.' },
      { title: 'Collect the waiver', detail: 'The student signs the waiver and health questions before the first session.' },
      { title: 'Make the wind call', detail: 'Sessions outside your wind and direction limits are flagged; you confirm, move, or reschedule them.' },
      { title: 'Pick the kit', detail: 'The instructor chooses kite and harness size against the student\'s stored weight, from gear tracked by size.' },
      { title: 'Close the day', detail: 'Walk-in hire settles at the register and the day\'s revenue lands in reporting.' },
    ],
    outcomes: [
      { label: 'The wind call in one view', detail: 'Forecast, limits, and roster sit together instead of in three places.' },
      { label: 'Expensive gear stays tracked', detail: 'Kites and boards are tracked by unit, size, and service state.' },
      { label: 'No double-booked instructors', detail: 'Overlapping instructor assignments are refused when they\'re made.' },
      { label: 'Paperwork before the beach', detail: 'Waivers and health answers are signed before arrival.' },
    ],
    constraints: [
      'Wind window with both a minimum and a maximum safe speed',
      'Wind direction suitable for the teaching zone',
      'Kite size and harness matched to student weight and live wind',
      'Radio helmet and safety-boat availability per lesson',
      'Pre-paid instruction hours tracked per student',
    ],
    faqs: [
      { question: 'Can students book kitesurf lessons online?', answer: 'Yes. Lessons, courses, and taster sessions sell through your own booking widget with a deposit or full payment and land on the same sessions as front-desk bookings.' },
      { question: 'How does it handle the wind call?', answer: 'Each session shows the forecast wind speed and direction for your spot. You set a minimum and maximum wind and a usable direction range per activity, and sessions outside them are flagged. The decision to run, move, or cancel stays with you.' },
      { question: 'Does RidgeHQ pick the kite size automatically?', answer: 'No. It tracks kites and harnesses by size and stores each student\'s weight on their profile, so the instructor can choose quickly — the choice itself, which depends on the wind on the day, stays with the instructor.' },
      { question: 'Can we track pre-paid lesson hours?', answer: 'Not as an hours balance today. Customers can hold a credit balance, and courses are sold as products with their own sessions, but RidgeHQ doesn\'t yet draw down a block of instruction hours automatically.' },
      { question: 'Can we manage safety boats?', answer: 'Yes, as fleet assets with capacity, crew, inspection log, and alerts for licences or insurance expiring within 30 days. Linking a specific boat to a lesson\'s availability isn\'t automatic.' },
      { question: 'How do digital waivers work?', answer: 'Each student signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'sailing-schools',
    name: 'Sailing Schools',
    slug: 'sailing-schools',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Sailing school software',
    seoTitle: 'Sailing School Software: Courses, Fleet & Charters',
    metaDescription: 'Sailing school software that runs multi-day courses and charters on one fleet, tracks vessel inspection and insurance dates, and refuses double-booked skippers.',
    heroHeadline: 'From enrolment to the last tack, one system.',
    heroDescription: 'Generic booking tools struggle with summer courses, private coaching, and fleet charter at once. RidgeHQ keeps every service on one planner and one fleet so you sell across channels and keep sessions on time.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Vessels, inspection dates, and crew in one place',
      'Overlapping skipper and pilot assignments refused',
    ],
    painPoint: 'A sailing school is a scheduling puzzle: a five-day course needs the right boat for five days, a qualified skipper for the same five days, and no clash with a maintenance haul-out or a weekend charter. Run that across a fleet on a spreadsheet and something gets double-booked.',
    keyCapability: 'Courses, coaching, and charters share one planner and one fleet register — each vessel\'s capacity, crew, inspection, licence, and insurance dates sit beside the schedule, and a skipper can\'t be assigned to two overlapping sessions or trips.',
    relatedPlatformSlugs: ['gear-rentals', 'scheduling', 'staff'],
    representativeFlow: [
      'A student books a five-day course online and pays a deposit.',
      'The course\'s sessions are created across the week in the planner.',
      'A skipper is assigned to each session; an overlapping assignment is refused.',
      'The vessel\'s inspection, licence, and insurance dates are visible, with alerts before they lapse.',
      'At the end of the week the instructor marks the student completed and a certification record is created.',
    ],
    featureSections: [
      {
        heading: 'Courses, coaching, and charters on one calendar',
        body: 'Summer courses, private coaching, and charters compete for the same boats and the same skippers. Putting them on one planner, sold through one checkout, is what stops the weekend charter landing on a course boat.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Courses with dated variants, attendance tracking, and completion records',
        ],
      },
      {
        heading: 'A fleet register that watches the paperwork',
        body: 'Every vessel carries its passenger capacity, registration, crew, and inspection history. RidgeHQ flags overdue inspections and licences or insurance expiring within 30 days, so a lapse is caught in the office rather than at the pontoon.',
        points: [
          'Vessels with capacity, registration, photo, and assigned crew',
          'Inspection log with next-due date; overdue inspections flagged',
          'Alerts for licence and insurance expiring within 30 days',
          'Smaller craft and kit tracked as gear units with maintenance records',
          'Trips with a pilot and destination, recurring departures, and attendee email',
        ],
      },
      {
        heading: 'Students and skippers on the same record',
        body: 'Qualifications matter on the water. Products can require a minimum level, the booking form asks for it, and the roster shows each student\'s certification — while the planner refuses to put one skipper in two places.',
        points: [
          'Products can require a skill level; licence number and level asked only where needed',
          'Certification records with level and verifying staff member',
          'Overlap checks for instructors and pilots',
          'Wind, wave, and tide context for the session\'s spot, with per-activity thresholds',
          'Per-participant waivers with typed signature and conditional questions',
        ],
      },
    ],
    workflow: [
      { title: 'Book online', detail: 'A student books a course or charter, pays a deposit, and signs the waiver.' },
      { title: 'Confirm on payment', detail: 'The order confirms once the payment succeeds; the balance is tracked against it.' },
      { title: 'Build the week', detail: 'Course sessions are created or cloned across the week in the planner.' },
      { title: 'Assign skippers', detail: 'Skippers and instructors are assigned per session; overlaps are refused.' },
      { title: 'Check the boat', detail: 'The vessel\'s inspection, licence, and insurance status are in view before departure.' },
      { title: 'Sign off', detail: 'Completion is recorded per student, creating a certification record, and the day closes into reporting.' },
    ],
    outcomes: [
      { label: 'No double-booked skippers', detail: 'Overlapping assignments are refused when they are made.' },
      { label: 'Compliance dates in view', detail: 'Inspection, licence, and insurance dates are tracked and flagged before they lapse.' },
      { label: 'One fleet, every service', detail: 'Courses, coaching, and charters plan against the same boats.' },
      { label: 'Completion on record', detail: 'Course completions create certification records on the student\'s profile.' },
    ],
    constraints: [
      'Vessel availability against courses, charters, and maintenance blocks',
      'Skipper and instructor qualification requirements per vessel',
      'Minimum and maximum crew limits for specific boats',
      'Inspection, licence, and insurance expiry dates per vessel',
      'Multi-day course blocks spanning consecutive days',
    ],
    faqs: [
      { question: 'Can RidgeHQ run multi-day sailing courses?', answer: 'Yes. Courses are sold as products with dated variants; their sessions sit in the planner across the week, attendance is tracked, and a completed course creates a certification record for the student.' },
      { question: 'Does it stop a boat being double-booked?', answer: 'Skippers and pilots can\'t be assigned to overlapping sessions or trips. Boat capacity is tracked per vessel, and trips carry their own capacity computed from their sessions; you allocate vessels in the planner.' },
      { question: 'How does it track vessel compliance?', answer: 'Each vessel has an inspection log with a next-due date, plus licence and insurance expiry dates. RidgeHQ flags overdue inspections and anything expiring within 30 days.' },
      { question: 'Can we require a sailing qualification before booking?', answer: 'Yes. A product can require a minimum skill level; the booking form then asks for the participant\'s level and licence number, and the roster shows it.' },
      { question: 'Can it show conditions for our sailing area?', answer: 'Yes. Sessions show wind, wave, and tide context for their spot, and per-activity thresholds flag sessions outside your limits.' },
      { question: 'How do digital waivers work?', answer: 'Each participant signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'windsurf-schools',
    name: 'Windsurf Schools',
    slug: 'windsurf-schools',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Windsurf school booking software',
    seoTitle: 'Windsurf School Booking Software & Rental POS',
    metaDescription: 'Windsurf school booking software for lessons and fast walk-in board and rig hire from one fleet, tracked by unit, size, and service status.',
    heroHeadline: 'Run a high-volume watersports centre at full speed.',
    heroDescription: 'Built for busy lesson and rental floors — windsurf, wingfoil, SUP. Sell through more channels, keep one live schedule for the whole team, and run clean check-ins without spreadsheet chaos.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Lessons and walk-in hire share one fleet',
      'Every board and rig tracked by unit and status',
    ],
    painPoint: 'A busy windsurf centre turns over gear all day and rents storage racks all season, while also teaching wind-dependent lessons. On paper you never quite know what is on the water, what is due back, or whether the board a lesson needs is already out with a walk-in.',
    keyCapability: 'Boards, rigs, and wetsuits are tracked as individual units with sizes and service status, and lessons and walk-in hire draw from the same inventory — so the counter can see what\'s free before handing it over.',
    relatedPlatformSlugs: ['gear-rentals', 'payments'],
    representativeFlow: [
      'A walk-in rents a board and rig for two hours at the counter.',
      'The specific units are booked for that time window and leave availability.',
      'A lesson booked online for the afternoon sees the same inventory.',
      'A rig that comes back damaged gets a maintenance record and leaves availability.',
      'At close, the register reconciles and the day\'s hire and lessons land in reporting.',
    ],
    featureSections: [
      {
        heading: 'Fast counter hire on one inventory',
        body: 'A busy centre turns over gear all day. Rentals are booked against specific units for a date and time window, so the counter and the lesson schedule are reading the same rack.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Timed rentals of specific units, with dates and start and end times',
        ],
      },
      {
        heading: 'Every board and rig, by unit and state',
        body: 'Boards, sails, rigs, booms, and wetsuits are tracked as individual units with sizes. A unit out for repair is removed from availability the moment its maintenance record is opened and returns when it comes back.',
        points: [
          'Gear units with sizes and size-matched availability',
          'Weekly rental planner by unit',
          'Maintenance records with vendor, expected return, and overdue flags',
          'CSV export of the maintenance register',
          'Retail stock records for the shop',
        ],
      },
      {
        heading: 'Wind-aware lessons alongside the hire',
        body: 'Lessons share the planner with everything else, with wind and direction context for your spot and thresholds per activity, so the call to run, move, or cancel a lesson is made with the forecast beside it.',
        points: [
          'Wind speed and direction context, with minimum, maximum, and direction limits per activity',
          'Overlap checks on instructor assignments',
          'Per-participant waivers with typed signature and conditional questions',
          'Products can require a skill level, asked for only where needed',
          'Email everyone booked on a session from the planner',
        ],
      },
    ],
    workflow: [
      { title: 'Sell at the counter', detail: 'A walk-in hire or a lesson goes through the POS basket with rentals and retail on one ticket.' },
      { title: 'Book the units', detail: 'Rentals reserve specific units for the date and time window; online lessons see the same inventory.' },
      { title: 'Sign the waiver', detail: 'Each participant signs the waiver before going on the water.' },
      { title: 'Check the wind', detail: 'Lessons outside your wind limits are flagged; move or reschedule them in the planner.' },
      { title: 'Log the damage', detail: 'Damaged gear gets a maintenance record and leaves availability until it\'s returned.' },
      { title: 'Close the register', detail: 'The register closes and hire, lessons, and retail land in reporting.' },
    ],
    outcomes: [
      { label: 'Fewer surprises at the rack', detail: 'The counter sees what\'s free by unit and size before handing it over.' },
      { label: 'Damaged gear stays out', detail: 'Maintenance records keep broken units out of availability until they\'re back.' },
      { label: 'Lessons and hire agree', detail: 'One inventory means a lesson\'s board isn\'t rented to a walk-in.' },
      { label: 'A clean close', detail: 'Register close and reporting come from the same orders.' },
    ],
    constraints: [
      'Wind speed and direction thresholds for beginner vs advanced lessons',
      'Board volume and rig size matched to student weight and skill',
      'Shared fleet split between taught lessons and walk-in hire',
      'Return times and overdue tracking for items on the water',
      'Physical storage rack availability and recurring billing',
    ],
    faqs: [
      { question: 'Can walk-in hire and lessons share the same gear?', answer: 'Yes. Rentals book specific units for a date and time window, and lessons and the counter read the same inventory, so the same board isn\'t promised twice.' },
      { question: 'How do we track damaged or serviced gear?', answer: 'Open a maintenance record for the unit. It leaves availability immediately, is flagged if its expected return passes, and comes back when you mark it returned. The register exports to CSV.' },
      { question: 'Can we rent storage racks to regular customers?', answer: 'Not as a dedicated storage feature today. Customer profiles can record gear they store with you, but rack rental isn\'t tracked as its own inventory.' },
      { question: 'Does it show wind conditions for lessons?', answer: 'Yes. Sessions show wind speed and direction for your spot, with per-activity minimum, maximum, and direction limits that flag sessions outside them.' },
      { question: 'How do digital waivers work?', answer: 'Each participant signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'outdoor-whitewater',
    name: 'Outdoor & Whitewater',
    slug: 'outdoor-whitewater',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Rafting booking software',
    seoTitle: 'Rafting Booking Software for Outdoor Centres',
    metaDescription: 'Rafting booking software for group trips: online and desk sales on one schedule, rafts and vehicles tracked as assets, and a waiver for every participant.',
    heroHeadline: 'Run your outdoor centre in flow.',
    heroDescription: 'Rafting, canyoning, and guided kayak trips move fast, sell in groups, and depend on clean logistics. RidgeHQ keeps website sales, POS, agents, payments, and participant forms connected.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Rafts, vehicles, and guides on one planner',
      'A signed waiver for every participant',
    ],
    painPoint: 'A single rafting or canyoning trip is a logistics chain: enough boats for the headcount, enough guides for the ratio, enough shuttle seats to reach the put-in, and a signed waiver for every person. Miss one link and the trip runs short-handed or leaves someone at the depot.',
    keyCapability: 'Group bookings, trips, guides, and assets live in one planner — trips carry their pilot or driver and destination, guides can\'t be double-booked, and every participant signs a waiver tied to the booking before they reach the put-in.',
    relatedPlatformSlugs: ['gear-rentals', 'staff', 'customers-participants'],
    representativeFlow: [
      'A group of eight books a rafting trip online with a shuttle add-on.',
      'Each participant receives and signs the waiver and medical questions.',
      'The trip\'s sessions are grouped with a driver and destination.',
      'Guides are assigned; an overlapping assignment is refused.',
      'On the day, the roster shows every participant and their waiver status.',
    ],
    featureSections: [
      {
        heading: 'Group bookings from every channel',
        body: 'Rafting and canyoning sell in groups, through your site, the desk, and hotels or agents. All of them write to the same trips, so a group sold by an agent is visible to the desk immediately.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Add-ons such as a shuttle or photos, mandatory or optional, attached to the trip product',
        ],
      },
      {
        heading: 'Trips, guides, and assets in one planner',
        body: 'A trip is a group of sessions with its own driver or pilot and destination. Guides are assigned in the same planner, with overlaps refused, and rafts, vehicles, and other assets are tracked with their capacity and paperwork.',
        points: [
          'Trips with a pilot or driver, destination spot, and capacity from their sessions',
          'Overlap checks on guide and pilot assignments',
          'Rafts, vehicles, and other assets tracked as fleet with capacity and crew',
          'Vehicle licence and insurance expiry alerts, and inspection logs',
          'Recurring departures and attendee email for each trip',
        ],
      },
      {
        heading: 'Every participant accounted for',
        body: 'Group trips fail on paperwork. Every participant has their own waiver on the booking, with a medical questionnaire and conditional questions, and the roster shows who still needs to sign.',
        points: [
          'Per-participant waivers with typed signature and medical questions',
          'Conditional questions that appear only when an earlier answer requires them',
          'Products can require a minimum experience level, asked for where needed',
          'Printable roster per session',
          'Changes to a paid group booking create a credit note',
        ],
      },
    ],
    workflow: [
      { title: 'Book the group', detail: 'A group books online or through an agent and adds any shuttle or extras.' },
      { title: 'Confirm on payment', detail: 'The order confirms once the payment succeeds.' },
      { title: 'Collect waivers', detail: 'Every participant signs their own waiver and medical questions.' },
      { title: 'Build the trip', detail: 'Sessions are grouped into a trip with a driver and destination.' },
      { title: 'Assign guides', detail: 'Guides are assigned in the planner; overlapping assignments are refused.' },
      { title: 'Run and close', detail: 'The roster shows waiver status on the day, and the trip\'s revenue lands in reporting by origin.' },
    ],
    outcomes: [
      { label: 'Nobody unsigned at the put-in', detail: 'Waivers are per participant and visible on the roster.' },
      { label: 'No double-booked guides', detail: 'Guide and driver overlaps are refused when assigned.' },
      { label: 'Assets with paperwork in view', detail: 'Vehicle licences, insurance, and inspections are tracked and flagged.' },
      { label: 'Agent sales in the same place', detail: 'Agent bookings land on the same trips with their commission recorded.' },
    ],
    constraints: [
      'Water levels and flow rates for the day\'s call',
      'Guide-to-client ratios that vary by river section and activity',
      'Guide qualification per section or activity',
      'Shuttle vehicle seat capacity',
      'Waiver completion for every participant before departure',
    ],
    faqs: [
      { question: 'How does RidgeHQ work as rafting booking software?', answer: 'Groups book online, at the desk, or through agents into the same trips. Each participant signs their own waiver, guides and drivers are assigned in the planner with overlap checks, and vehicles and rafts are tracked as assets.' },
      { question: 'Does the booking headcount reserve rafts, guides, and shuttle seats automatically?', answer: 'No. The trip\'s capacity comes from its sessions and the roster shows the headcount, but allocating rafts, guides, and vehicle seats is still done by your team in the planner. A shuttle can be sold as an add-on to the trip.' },
      { question: 'Can we enforce a guide-to-client ratio?', answer: 'Not automatically today. Size each session\'s capacity to your ratio; RidgeHQ will refuse a double-booked guide but does not calculate ratios.' },
      { question: 'Can every participant sign a waiver before the trip?', answer: 'Yes. Waivers are per participant on the booking, with medical questions and conditional follow-ups, and the roster shows who has signed.' },
      { question: 'Can we track our vehicles\' paperwork?', answer: 'Yes. Vehicles are fleet assets with registration, crew, an inspection log, and alerts when licences or insurance expire within 30 days.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'ski-schools',
    name: 'Ski Schools',
    slug: 'ski-schools',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Ski school software',
    seoTitle: 'Ski School Software: Bookings, Instructors & Tracking',
    metaDescription: 'Ski school software for lessons and multi-day courses: each student\'s level on the roster, instructors protected from double-booking, and fast desk sales.',
    heroHeadline: 'Handle peak season from the first call to the last run.',
    heroDescription: 'Generic tools do not handle ski and snowboard lessons, multi-day courses, meeting points, and constant last-minute changes. RidgeHQ brings bookings, scheduling, payments, and admin into one flow.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Student level on every roster',
      'Built for the morning desk rush',
    ],
    painPoint: 'Ski school demand arrives in a wall at 8:45 a.m.: families wanting privates and group classes at different levels, in different languages, all for the same slot. Matching every booking to the right instructor by hand, at that speed, is where the mistakes happen.',
    keyCapability: 'Lessons, multi-day courses, and desk sales share one planner — products can require a minimum level, the roster shows each student\'s level, and an instructor can\'t be assigned to two sessions at once.',
    relatedPlatformSlugs: ['scheduling', 'staff'],
    representativeFlow: [
      'A family books group lessons online for three children at different levels.',
      'Each lesson product asks for the child\'s level where the class requires it.',
      'At 8:45 the desk sells walk-in privates on the POS against the same sessions.',
      'Instructors are assigned; an overlapping assignment is refused.',
      'Each instructor\'s roster shows their students and levels.',
    ],
    featureSections: [
      {
        heading: 'Desk and online sales on one availability',
        body: 'Demand arrives in a wall each morning. When online bookings and desk sales write to the same sessions, the desk never sells a place the website already sold.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Seasons in the catalogue for the winter calendar',
        ],
      },
      {
        heading: 'Levels on the roster, not in someone\'s head',
        body: 'Placing the right student in the right group needs their level at hand. Products can require a minimum level; the booking form asks for it only where it matters, and every session roster shows each student\'s level.',
        points: [
          'Skill-level requirements on lesson products',
          'Level asked at booking only where required, online and at the desk',
          'Printable session rosters with student levels',
          'Courses with attendance tracking and completion records',
          'Staff profiles carry the languages each instructor speaks',
        ],
      },
      {
        heading: 'Instructors and multi-day courses without clashes',
        body: 'Multi-day courses tie an instructor to the same group for several days. The planner shows the week by activity or by instructor, clones a week forward, and refuses an assignment that overlaps another session.',
        points: [
          'Weekly planner by activity or by instructor',
          'Overlap checks on every instructor assignment',
          'Clone or bulk-update sessions for recurring weeks',
          'Instructor fees calculated from assigned sessions',
          'Per-participant waivers with typed signature and conditional questions',
        ],
      },
    ],
    workflow: [
      { title: 'Book ahead', detail: 'Families book lessons online with each child\'s level where the class requires it.' },
      { title: 'Sell the rush', detail: 'Walk-ins buy privates and group places at the desk against the same sessions.' },
      { title: 'Assign instructors', detail: 'Instructors are assigned per session; overlaps are refused.' },
      { title: 'Hand out rosters', detail: 'Each instructor\'s roster shows their students and levels.' },
      { title: 'Track the course', detail: 'Attendance is tracked across a multi-day course and completion is recorded.' },
      { title: 'Close and pay', detail: 'The register closes and instructor fees are calculated from the sessions taught.' },
    ],
    outcomes: [
      { label: 'A calmer 8:45', detail: 'Desk and online sales draw from the same sessions.' },
      { label: 'Levels at hand', detail: 'Every roster shows each student\'s level.' },
      { label: 'No double-booked instructors', detail: 'Overlapping assignments are refused.' },
      { label: 'Fees from real sessions', detail: 'Instructor pay is calculated from what they taught.' },
    ],
    constraints: [
      'Instructor certification levels (beginner, all-mountain, off-piste)',
      'Instructor and session language',
      'Separate morning and afternoon scheduling blocks',
      'Group class size and ratio limits',
      'Student ability level captured before assignment',
    ],
    faqs: [
      { question: 'Does RidgeHQ match instructors to students automatically?', answer: 'No. RidgeHQ shows each student\'s level on the roster, keeps each instructor\'s languages on their profile, and refuses overlapping assignments — choosing which instructor takes which group stays with your ski school director.' },
      { question: 'Can we require a level for a lesson?', answer: 'Yes. A product can require a minimum skill level; the booking form then asks for the student\'s level, online and at the desk, and the roster shows it.' },
      { question: 'Can it handle multi-day courses?', answer: 'Yes. Courses are sold with dated variants, their sessions sit across the week in the planner, attendance is tracked, and completion is recorded per student.' },
      { question: 'How are instructor fees handled?', answer: 'Fee groups hold per-session, per-hour, or commission rates per activity. RidgeHQ calculates each instructor\'s fees from the sessions they were assigned and flags any session missing a rate.' },
      { question: 'Does it sell lift passes?', answer: 'No. RidgeHQ runs your lessons, courses, rentals, and retail; lift tickets stay with the resort\'s own system.' },
      { question: 'How do digital waivers work?', answer: 'Each participant signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'dive-resorts',
    name: 'Dive Resorts',
    slug: 'dive-resorts',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Dive resort software',
    seoTitle: 'Dive Resort Software: Rooms, Dives & One Folio',
    metaDescription: 'Dive resort software that runs rooms and the dive schedule on one system, with Stay & Dive packages bundling accommodation, diving, and rental gear.',
    heroHeadline: 'A hotel and a dive centre, running as one.',
    heroDescription: 'RidgeHQ brings website sales, on-site POS, boat operations, guest paperwork, and the daily close into one system — purpose-built for dive operations and flexible for resort stays with add-ons.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Rooms and dive operations on one system',
      'Stay & Dive packages in one checkout',
    ],
    painPoint: 'A dive resort runs a hotel and a dive centre at once. When the beds live in one system and the boats in another, package dives get miscounted, a guest gets billed twice, and reception and the dive desk spend the week reconciling by hand.',
    keyCapability: 'Rooms, dives, and rental gear are sold and planned in one system — a package product bundles the accommodation and rental components, and the room calendar and the dive planner read the same bookings.',
    relatedPlatformSlugs: ['scheduling', 'payments', 'customers-participants'],
    representativeFlow: [
      'A guest books a seven-night Stay & Dive package online.',
      'The package reserves the room and includes the bundled rental gear.',
      'The guest signs the waiver and medical form before arrival.',
      'Each day\'s dives are planned as trips with a pilot and dive site.',
      'Boat manifests are generated from the confirmed divers, with certifications and sizes.',
    ],
    featureSections: [
      {
        heading: 'Beds and boats in one checkout',
        body: 'When rooms live in one system and dives in another, packages get miscounted and guests get billed twice. In RidgeHQ a package product bundles accommodation and rental components, and the room calendar and the dive planner read from the same order.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Package products bundling accommodation and rental components, with optional add-ons',
        ],
      },
      {
        heading: 'Rooms with their own calendar',
        body: 'Room types and units have a weekly calendar with booking, maintenance, and unavailable blocks. It stays separate from the dive planner, but is one click away from it.',
        points: [
          'Room types and units with a weekly calendar',
          'Booking, maintenance, and unavailable blocks per room',
          'Accommodation dates on the order line',
          'Linked from the dive planner as a related calendar',
          'Revenue by origin across rooms, dives, and retail',
        ],
      },
      {
        heading: 'Dive operations that match the guest list',
        body: 'The dive side works like a dive centre: trips with pilots and sites, manifests generated from confirmed divers, certifications and sizes stored once per guest.',
        points: [
          'Trips with pilot, dive site, and capacity from their sessions',
          'Boat manifests with certification and kit sizes',
          'Certification records and equipment sizing per guest',
          'Per-participant waivers and medical questionnaire',
          'Trip gear prep list from each diver\'s needs',
        ],
      },
    ],
    workflow: [
      { title: 'Book the package', detail: 'A guest books a Stay & Dive package online and pays a deposit.' },
      { title: 'Hold the room', detail: 'The package\'s accommodation is reserved on the room calendar.' },
      { title: 'Prepare the diver', detail: 'Waiver, medical form, certifications, and sizes are collected before arrival.' },
      { title: 'Plan the dives', detail: 'Daily dives are planned as trips with a pilot and site.' },
      { title: 'Generate manifests', detail: 'Manifests come from confirmed divers with certifications and sizes.' },
      { title: 'Close out', detail: 'Balances settle at the desk and revenue lands in reporting by origin.' },
    ],
    outcomes: [
      { label: 'One order per guest', detail: 'Room, diving, and gear sit on one package order.' },
      { label: 'Reception and dive desk agree', detail: 'Both read the same bookings.' },
      { label: 'Manifests from real bookings', detail: 'The boat list is generated from confirmed divers.' },
      { label: 'Paperwork done before arrival', detail: 'Waivers and medical forms are signed ahead.' },
    ],
    constraints: [
      'Room availability, occupancy type, and turnaround times',
      'Package inclusion limits (dives included, nitrox, equipment)',
      'Boat and guide capacity shared between resort guests and day guests',
      'Certification and medical clearance per dive or course',
      'Tide, visibility, and water temperature for each site',
    ],
    faqs: [
      { question: 'Can we sell Stay & Dive packages?', answer: 'Yes. A package product can bundle accommodation and rental components, with optional or mandatory add-ons, and it sells through the same checkout as everything else.' },
      { question: 'Does RidgeHQ count down package dives as they\'re used?', answer: 'Not automatically today. The package is one order with its components; dives are planned as sessions and trips, and you track usage in the planner.' },
      { question: 'Does it replace our hotel system?', answer: 'It manages room types, units, and a booking calendar for operators whose rooms are part of the dive business. It isn\'t a full hotel property management system — there is no channel manager for OTAs or a guest folio across a restaurant and bar.' },
      { question: 'Can it produce boat manifests?', answer: 'Yes. A manifest is generated per session from its confirmed participants, with certifications and kit sizes, linked to the vessel.' },
      { question: 'How do digital waivers work?', answer: 'Each diver signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'surf-camps',
    name: 'Surf Camps',
    slug: 'surf-camps',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Surf camp booking software',
    seoTitle: 'Surf Camp Booking Software: Beds, Lessons & Transfers',
    metaDescription: 'Surf camp booking software where one package books the bed, the week of lessons, and board hire, with add-ons like an airport transfer.',
    heroHeadline: 'From packages to daily schedules, one flow.',
    heroDescription: 'Beds, daily lessons, gear, and guest prep kept together. RidgeHQ sells week stays as packages with add-ons, collects deposits, captures guest details up front, and runs daily rosters without spreadsheets.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Beds, lessons, and gear in one package',
      'Add-ons like airport transfers',
    ],
    painPoint: 'A surf camp week has a lot of moving parts per guest: a bed, an airport pickup, a lesson group at their level, and a note for the kitchen. Run that on a booking tool plus three spreadsheets and every changeover day is a fire drill.',
    keyCapability: 'A camp package bundles the bed and the rental gear and carries add-ons like an airport transfer, while the week\'s lessons sit in the planner with tide and swell context — so a changeover day is a roster, not a fire drill.',
    relatedPlatformSlugs: ['bookings-pos', 'scheduling', 'customers-participants'],
    representativeFlow: [
      'A guest books a one-week camp package with an airport-transfer add-on.',
      'The package reserves their bed and includes board hire.',
      'They sign the waiver and answer your questions before arrival.',
      'The week\'s lessons sit in the planner with tide and swell for your break.',
      'On changeover day the room calendar and the lesson roster show who arrives and leaves.',
    ],
    featureSections: [
      {
        heading: 'A whole week in one package',
        body: 'A surf-camp week has a lot of moving parts per guest. Packaging the bed and the gear, and selling extras as add-ons, keeps them on one order instead of a booking tool plus three spreadsheets.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Camp products bundling accommodation and rental components, with optional or mandatory add-ons such as a transfer',
        ],
      },
      {
        heading: 'Rooms and lessons that change over together',
        body: 'Room types and units have their own calendar with booking and maintenance blocks; lessons sit in the planner with the forecast. Both read the same orders, so arrivals and departures line up.',
        points: [
          'Room calendar with booking, maintenance, and unavailable blocks',
          'Tide, swell, and wind context on each lesson, with per-activity thresholds',
          'Overlap checks on instructor assignments',
          'Email everyone booked on a session from the planner',
          'Clone a week of sessions forward for the next intake',
        ],
      },
      {
        heading: 'Guest details before they land',
        body: 'Most changeover stress is information collected too late. Waivers with conditional questions, a medical form, and stored sizes are captured with the booking.',
        points: [
          'Per-participant waivers with typed signature',
          'Conditional questions — for example, ask for allergy details only when a guest says yes',
          'Equipment sizes stored on the guest profile',
          'Boards and wetsuits tracked by unit and size',
          'Changes to a paid package create a credit note',
        ],
      },
    ],
    workflow: [
      { title: 'Book the week', detail: 'A guest books a camp package online with any add-ons and pays a deposit.' },
      { title: 'Hold the bed', detail: 'The package\'s accommodation is reserved on the room calendar.' },
      { title: 'Collect details', detail: 'Waiver, health questions, and sizes are captured before arrival.' },
      { title: 'Plan lessons', detail: 'The week\'s lessons sit in the planner with tide and swell context.' },
      { title: 'Run changeover', detail: 'The room calendar and rosters show who arrives and leaves.' },
      { title: 'Close the week', detail: 'Balances settle and revenue lands in reporting.' },
    ],
    outcomes: [
      { label: 'One order per guest', detail: 'Bed, gear, and extras on a single package.' },
      { label: 'Calmer changeovers', detail: 'Rooms and lessons read the same bookings.' },
      { label: 'Details collected early', detail: 'Waivers and conditional questions are answered before arrival.' },
      { label: 'Weeks you can reuse', detail: 'Clone a week of sessions forward for the next intake.' },
    ],
    constraints: [
      'Bed and room capacity across dorms and private rooms',
      'Instructor ratios for the included lessons',
      'Transfer vehicle seat capacity for arrivals and departures',
      'Tide and swell suitability for each group\'s level',
      'Rental board and wetsuit stock reserved for the week',
    ],
    faqs: [
      { question: 'Can one booking cover the bed, lessons, and gear?', answer: 'Yes. A camp product bundles accommodation and rental components, and extras such as an airport transfer can be added as add-ons, all on one order.' },
      { question: 'How do we capture dietary needs?', answer: 'Add them as questions on your waiver form. Conditional questions only appear when needed — for example, ask for allergy details only when a guest answers yes.' },
      { question: 'Does RidgeHQ book the airport transfer with a driver?', answer: 'It sells the transfer as an add-on on the order. Scheduling the driver and vehicle is done by your team, and vehicles can be tracked as fleet assets.' },
      { question: 'Can it show surf conditions for lessons?', answer: 'Yes. Sessions show tide, swell, and wind for your spot, and per-activity thresholds flag sessions outside your limits.' },
      { question: 'How do digital waivers work?', answer: 'Each guest signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'kayak-rental-tours',
    name: 'Kayak Rental & Tours',
    slug: 'kayak-rental-tours',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Kayak rental software',
    seoTitle: 'Kayak Rental Software for Kayak & Canoe Tours',
    metaDescription: 'Kayak rental software for kayak and canoe tours and walk-in hire: one boat inventory by unit, guides protected from double-booking, and waivers at the desk.',
    heroHeadline: 'Run your kayak and paddle operation at full speed.',
    heroDescription: 'One booking and operations system for kayak and SUP rentals and guided tours. Availability, payments, customer details, and the daily run stay unified from the front desk to the dock.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'One inventory for tours and walk-in hire',
      'Guides protected from double-booking',
    ],
    painPoint: 'A kayak operation sells guided tours and hires boats by the hour from the same rack. Without one shared inventory, a tour turns up needing ten doubles that walked out the door an hour earlier, and the desk finds out at the water.',
    keyCapability: 'Kayaks, canoes, and boards are tracked as individual units shared between guided tours and hourly hire — so a tour and a walk-in can\'t both be promised the same boat, and guides can\'t be put on two tours at once.',
    relatedPlatformSlugs: ['gear-rentals', 'staff'],
    representativeFlow: [
      'A couple books a sunset tour online.',
      'A walk-in hires a double kayak for two hours at the desk.',
      'The hire reserves a specific unit for that time window.',
      'Guides are assigned to the tour; an overlapping assignment is refused.',
      'Every participant signs the waiver before launching.',
    ],
    featureSections: [
      {
        heading: 'Tours and hire from one rack',
        body: 'Tours and hourly hire compete for the same boats. Timed rentals book specific units for a date and time window, so the desk and the tour schedule read the same rack.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Timed rentals of specific units with dates and start and end times',
        ],
      },
      {
        heading: 'Every boat, by unit and state',
        body: 'Kayaks, canoes, SUPs, paddles, and buoyancy aids are tracked as units with sizes. Damaged boats get a maintenance record and leave availability until they\'re fixed.',
        points: [
          'Gear units with sizes and size-matched availability',
          'Weekly rental planner by unit',
          'Maintenance records with expected return and overdue flags',
          'Support boats and vehicles tracked as fleet assets',
          'Licence, insurance, and inspection alerts for fleet',
        ],
      },
      {
        heading: 'Guided tours with the right people',
        body: 'Tours are sessions in the planner with their guides, roster, and conditions. Guides can\'t be double-booked, and every participant signs their own waiver.',
        points: [
          'Overlap checks on guide assignments',
          'Wind, wave, and tide context for the launch spot',
          'Per-participant waivers with typed signature and conditional questions',
          'Products can require a minimum experience level',
          'Email everyone booked on a tour from the planner',
        ],
      },
    ],
    workflow: [
      { title: 'Book or walk in', detail: 'Tours sell online; hire sells at the desk against the same inventory.' },
      { title: 'Reserve the boat', detail: 'Hire books a specific unit for a time window.' },
      { title: 'Sign the waiver', detail: 'Each participant signs before launching.' },
      { title: 'Assign guides', detail: 'Guides are assigned to tours; overlaps are refused.' },
      { title: 'Check conditions', detail: 'Tours outside your wind or wave limits are flagged.' },
      { title: 'Close the day', detail: 'Hire and tours settle at the register and land in reporting.' },
    ],
    outcomes: [
      { label: 'No boat promised twice', detail: 'Tours and hire share one inventory by unit.' },
      { label: 'No double-booked guides', detail: 'Overlaps refused when assigned.' },
      { label: 'Damaged boats stay out', detail: 'Maintenance records keep them unavailable.' },
      { label: 'Waivers at launch', detail: 'Every participant signed before they\'re on the water.' },
    ],
    constraints: [
      'Separate stock of single vs double kayaks',
      'Turnaround time for cleaning and checking boats between hires',
      'Guide availability and guide-to-client ratios per tour',
      'Return times and overdue tracking for boats on the water',
      'Waiver completion for every participant before launch',
    ],
    faqs: [
      { question: 'Can tours and walk-in hire share the same kayaks?', answer: 'Yes. Boats are tracked as individual units, and timed rentals reserve a specific unit for a time window, so the desk and the tour schedule read the same rack.' },
      { question: 'Can we schedule guides at a set ratio?', answer: 'RidgeHQ refuses double-booked guides but doesn\'t calculate ratios. Size each tour\'s capacity to your ratio and assign guides in the planner.' },
      { question: 'Does it work for canoes and SUPs too?', answer: 'Yes. Gear types are yours to define — kayaks, canoes, SUPs, paddles, buoyancy aids — each tracked by unit and size.' },
      { question: 'Can it show conditions for our launch spot?', answer: 'Yes. Sessions show wind, wave, and tide context for their spot, with per-activity thresholds that flag tours outside your limits.' },
      { question: 'How do digital waivers work?', answer: 'Each participant signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'bike-rental-tours',
    name: 'Bike Rental & Tours',
    slug: 'bike-rental-tours',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Bike rental software',
    seoTitle: 'Bike Rental Software: Fleet, Sizes & Tours',
    metaDescription: 'Bike rental software that tracks every bike by unit, frame size, and service state, books a specific bike for a time window, and runs guided tours.',
    heroHeadline: 'Run your bike rental shop at full speed.',
    heroDescription: 'Stop managing rentals across paper, chat apps, and spreadsheets. RidgeHQ puts rentals, fleet availability, payments, and staff scheduling on one live calendar — for the shop floor and guided tours.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Every bike tracked as its own unit',
      'Size and service state drive availability',
    ],
    painPoint: 'A bike fleet is not interchangeable stock — it is individual assets, each with a frame size, a service history, and a battery that needs turnaround time. Booking "an e-bike" and sorting out which one on the morning of pickup is how you hand over a bike with a flagged brake.',
    keyCapability: 'Every bike is tracked as an individual unit with its frame size and service state, and a rental books a specific bike for a time window — so the bike handed over is the one that was booked, and one flagged for service never goes out.',
    relatedPlatformSlugs: ['gear-rentals', 'bookings-pos'],
    representativeFlow: [
      'A rider books a medium e-bike for a full day online.',
      'A specific medium bike is reserved for that date and time window.',
      'A bike with a brake issue gets a maintenance record and leaves availability.',
      'A guided tour is scheduled with a guide; overlaps are refused.',
      'The rider signs the waiver, and the day\'s hire lands in reporting.',
    ],
    featureSections: [
      {
        heading: 'Book a specific bike, not just a category',
        body: 'A bike fleet is individual assets, not interchangeable stock. Rentals book a specific unit for a date and time window, and availability is checked size-for-size.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Timed rentals of a specific bike, with dates and start and end times',
        ],
      },
      {
        heading: 'Service state that controls availability',
        body: 'Opening a maintenance record takes a bike out of availability immediately and puts it back when it\'s returned. Overdue repairs are flagged and the register exports to CSV.',
        points: [
          'Bikes tracked as units with frame size',
          'Maintenance records with vendor, expected return, and overdue flags',
          'Weekly rental planner by unit',
          'Support vehicles as fleet assets with licence and insurance alerts',
          'Retail stock records for accessories',
        ],
      },
      {
        heading: 'Guided tours on the same system',
        body: 'Tours run in the planner with guides, rosters, and per-participant waivers, drawing on the same bikes as hire.',
        points: [
          'Overlap checks on guide assignments',
          'Trips with a driver or pilot and destination',
          'Per-participant waivers with typed signature and conditional questions',
          'Email everyone booked on a tour from the planner',
          'Changes to a paid booking create a credit note',
        ],
      },
    ],
    workflow: [
      { title: 'Book online', detail: 'A rider books a bike or tour online and pays.' },
      { title: 'Reserve the bike', detail: 'A specific bike of the right size is reserved for the time window.' },
      { title: 'Sign the waiver', detail: 'The rider signs before pickup.' },
      { title: 'Check service', detail: 'Bikes with open maintenance records are out of availability.' },
      { title: 'Run the tour', detail: 'Guides are assigned; overlaps refused.' },
      { title: 'Close the day', detail: 'Returns, hire, and retail settle at the register and land in reporting.' },
    ],
    outcomes: [
      { label: 'The right bike handed over', detail: 'Rentals book a specific unit, not a category.' },
      { label: 'No flagged bike goes out', detail: 'Maintenance records remove it from availability.' },
      { label: 'Tours and hire agree', detail: 'Both draw on the same fleet.' },
      { label: 'A clean close', detail: 'Register and reports come from the same orders.' },
    ],
    constraints: [
      'Frame size matching (S / M / L / XL) per booking',
      'Battery and cleaning turnaround time between hires',
      'Service history and safety checks per bike',
      'Shared fleet across rentals, walk-in hire, and guided tours',
      'Security deposit pre-authorisation and release',
    ],
    faqs: [
      { question: 'Does RidgeHQ track bikes individually?', answer: 'Yes. Each bike is a unit with its own frame size and service history, and rentals reserve a specific unit for a date and time window.' },
      { question: 'Can we take a security deposit or pre-authorise a card?', answer: 'Not as a separate card hold today. You can take a deposit as part of the booking payment, but RidgeHQ doesn\'t pre-authorise and later release a damage deposit.' },
      { question: 'How do we keep a bike with a problem off the road?', answer: 'Open a maintenance record. The bike leaves availability immediately, is flagged if its repair runs late, and returns to availability when marked returned.' },
      { question: 'Can we track e-bike batteries?', answer: 'Batteries can be tracked as their own gear units with maintenance records, but RidgeHQ doesn\'t monitor charge or turnaround time automatically.' },
      { question: 'How do digital waivers work?', answer: 'Each rider signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
  {
    id: 'boat-rental-courses',
    name: 'Boat Rental & Courses',
    slug: 'boat-rental-courses',
    lastUpdated: '2026-10-06',
    searchKeyword: 'Boat rental software',
    seoTitle: 'Boat Rental Software for Charters & Courses',
    metaDescription: 'Boat rental software that runs charters and courses on one fleet, asks for licence details where a booking requires them, and flags expiring vessel paperwork.',
    heroHeadline: 'Run charters and skipper courses at full speed.',
    heroDescription: 'Stop juggling boat availability, course sessions, payments, and paperwork. RidgeHQ keeps charters and training in one place so you fill more dates, avoid double-bookings, and run smoother at the dock.',
    heroProofPoints: [
      '0% commission on direct bookings',
      'Licence details asked where a booking requires them',
      'Vessel inspection, licence, and insurance alerts',
    ],
    painPoint: 'Handing over a boat worth six figures depends on two things going right: the right licence on file for a bareboat charter, and a security deposit that is actually held. Chase both by email and one of them slips — the client arrives without the paperwork, or the deposit was never taken.',
    keyCapability: 'Charters and courses share one fleet register and one planner — a charter product can require a qualification so the booking form asks for the skipper\'s level and licence number, and each vessel\'s inspection, licence, and insurance dates are flagged before they lapse.',
    relatedPlatformSlugs: ['payments', 'customers-participants', 'gear-rentals'],
    representativeFlow: [
      'A client books a bareboat charter online and pays a deposit.',
      'The charter requires a qualification, so the form asks for their level and licence number.',
      'They sign the charter waiver with a typed signature.',
      'The vessel\'s inspection, licence, and insurance status are visible in the fleet register.',
      'After the charter the balance settles and the day lands in reporting.',
    ],
    featureSections: [
      {
        heading: 'Charters and courses through one checkout',
        body: 'Charters, skippered trips, and training courses compete for the same boats. Selling them through one checkout onto one planner keeps them from colliding.',
        points: [
          'Booking widget on your own website with live availability, deposit or full payment, and promo codes',
          'Front-desk POS for walk-ins, rentals, and retail on one basket, with register open and close',
          'Agent and partner bookings recorded with their commission for settlement',
          '0% platform commission on direct bookings',
          'Courses with dated variants, attendance, and completion records',
        ],
      },
      {
        heading: 'Qualifications asked for at booking',
        body: 'Bareboat hire depends on the right qualification. A product can require a minimum level; the booking form then asks for the client\'s level and licence number, and both are stored with the booking.',
        points: [
          'Skill-level requirement on charter and course products',
          'Level and licence number asked only where the product requires them',
          'Certification records with level and verifying staff member',
          'Per-participant waivers with typed signature and conditional questions',
          'Course completion creates a certification record',
        ],
      },
      {
        heading: 'A fleet register that watches the paperwork',
        body: 'Each vessel carries capacity, registration, crew, and inspection history, with alerts before paperwork lapses — so the office catches it, not the client at the pontoon.',
        points: [
          'Vessels with capacity, registration, and crew',
          'Inspection log with next-due date and overdue flags',
          'Licence and insurance expiry alerts within 30 days',
          'Trips with a skipper and destination; overlapping skippers refused',
          'Wind, wave, and tide context with per-activity thresholds',
        ],
      },
    ],
    workflow: [
      { title: 'Book the charter', detail: 'A client books online and pays a deposit.' },
      { title: 'Check the qualification', detail: 'Products that require it ask for the client\'s level and licence number.' },
      { title: 'Sign the waiver', detail: 'The client signs with a typed signature before handover.' },
      { title: 'Check the boat', detail: 'Inspection, licence, and insurance status are in view in the fleet register.' },
      { title: 'Plan skippered trips', detail: 'Skippers are assigned; overlaps refused.' },
      { title: 'Settle up', detail: 'The balance settles and the charter lands in reporting by origin.' },
    ],
    outcomes: [
      { label: 'Qualifications on file', detail: 'Licence details are captured at booking where they\'re required.' },
      { label: 'Paperwork that doesn\'t lapse quietly', detail: 'Vessel inspections, licences, and insurance are flagged.' },
      { label: 'No double-booked skippers', detail: 'Overlaps refused when assigned.' },
      { label: 'Charters and courses agree', detail: 'One fleet, one planner.' },
    ],
    constraints: [
      'Vessel availability and turnaround time between bookings',
      'Client licence and ID verification status',
      'Skipper and instructor availability for skippered work',
      'Inspection, licence, and insurance expiry per vessel',
      'Security deposit pre-authorisation and release',
    ],
    faqs: [
      { question: 'Can RidgeHQ check a charter client\'s licence?', answer: 'It collects it. A charter product can require a qualification, so the booking form asks for the client\'s level and licence number and stores them with the booking. Verifying the document itself is still done by your team at handover.' },
      { question: 'Can we hold a security deposit?', answer: 'Not as a pre-authorised card hold today. You can take a deposit as part of the booking payment, but RidgeHQ doesn\'t pre-authorise and later release a damage deposit.' },
      { question: 'Does it collect ID documents?', answer: 'No. Customer records store contact details, certifications with optional documents, and licence numbers; RidgeHQ doesn\'t collect or verify passports or ID cards.' },
      { question: 'How does it track vessel compliance?', answer: 'Each vessel has an inspection log with next-due dates plus licence and insurance expiry dates, and RidgeHQ flags overdue inspections and anything expiring within 30 days.' },
      { question: 'How do digital waivers work?', answer: 'Each client signs your waiver with a typed signature, attached to their booking. You can add a medical questionnaire and conditional questions that only appear when an earlier answer requires them. Waivers are part of the platform, not a paid add-on.' },
      { question: 'Do you charge commission on our bookings?', answer: 'No. Direct bookings through your own website carry 0% RidgeHQ commission. You pay your payment provider\'s normal processing fee and a flat subscription.' },
      { question: 'What happens to the money when a paid booking changes?', answer: 'The paid order is never silently rewritten. A change or cancellation produces a credit note against it, so your daily close and your accounts still reconcile.' },
      { question: 'What can the AI Copilot actually do?', answer: 'It reads your day — sessions, bookings, conditions — and answers questions about it. It can carry out actions such as rescheduling a session or moving a participant, each behind a confirm step, and reversible scheduling actions can be undone. Higher-risk actions — creating or cancelling a booking, or refunding a payment — are limited to managers and always need explicit confirmation; assistants connected over MCP cannot use them at all.' },
    ],
  },
];
